/// The generated C: the same text the Python writes, and a filter that runs.
///
/// Two checks, and the second is the one that matters. The text is compared
/// against files the Python tool generated for the same two designs, so a
/// changed constant or a dropped line shows up as a diff. Then the C is
/// actually compiled and run, and its output compared sample for sample
/// against the Dart model of the same filter -- which is the only way to know
/// that the coefficients came out in the order the loop reads them.
library;

import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:remez/src/c_export.dart';
import 'package:remez/src/controller.dart';
import 'package:remez/src/iir_core.dart' as iir;

/// The one line the two tools legitimately differ on.
String _normalise(String source) => source
    .replaceAll(' * Generated by remez.', ' * Generated by remez.py.');

final RegExp _number = RegExp(r'[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?');

/// Assert two generated sources are the same file.
///
/// Line for line and character for character, except that where a line differs
/// only in the *value* of its numbers they are compared as numbers, to a
/// relative 1e-12. The two implementations agree on the design to about that
/// and no further -- the taps differ in the last bit or two, as the golden
/// tests for the cores already record -- so demanding identical text would be
/// asserting something neither tool promises. Everything else, including where
/// each number sits and how it is punctuated, still has to match exactly.
void expectSameSource(String got, String want) {
  final a = _normalise(got).split('\n');
  final b = want.split('\n');
  expect(a.length, b.length, reason: 'line count');
  for (var i = 0; i < b.length; i++) {
    if (a[i] == b[i]) continue;
    // Whitespace runs collapse before comparing: the two tools write the
    // signed zero of a coefficient that is exactly zero differently -- one as
    // `-0` and the other as ` 0` -- and the `%g` space flag pads only the
    // non-negative, so the column shifts by one. Same value, same field, one
    // character of padding.
    String skeleton(String line) =>
        line.replaceAll(_number, 'N').replaceAll(RegExp(r'\s+'), ' ');
    expect(skeleton(a[i]), skeleton(b[i]), reason: 'line ${i + 1}');
    final numsA = _number.allMatches(a[i]).map((m) => double.parse(m[0]!));
    final numsB = _number.allMatches(b[i]).map((m) => double.parse(m[0]!));
    final pairs = numsA.toList();
    final wanted = numsB.toList();
    for (var k = 0; k < wanted.length; k++) {
      // Relative, with an absolute floor: a coefficient whose true value is
      // zero comes out as whatever each implementation's rounding left behind,
      // and 1e-16 against 3e-16 is agreement, not a factor of three.
      final tol = math.max(wanted[k].abs() * 1e-12, 1e-12);
      expect(pairs[k], closeTo(wanted[k], tol),
          reason: 'line ${i + 1}, number ${k + 1}');
    }
  }
}

DesignController _lowpass() => DesignController()..design();

DesignController _ellipticBandpass() {
  final c = DesignController();
  c.update(() {
    c.mode = Mode.iir;
    c.approximation = 'elliptic';
  });
  c.setResponse('bandpass');
  return c;
}

/// Compile [source], run [input] through it, and return what came back.
///
/// Raw f64 in, raw f64 out, which is the program's own interface. Returns null
/// when there is no C compiler to hand, so the suite still runs on a machine
/// without one -- the caller reports that rather than passing silently.
Float64List? _runC(String source, Float64List input, Directory dir) {
  final src = File('${dir.path}/filter.c')..writeAsStringSync(source);
  final exe = '${dir.path}/filter';
  // -ffp-contract=off: with contraction on, clang fuses the multiply-add in
  // the inner loop and the result stops being the one the model computes.
  final built = Process.runSync(
      'cc', ['-O2', '-ffp-contract=off', '-o', exe, src.path]);
  if (built.exitCode != 0) {
    if (built.stderr.toString().contains('not found')) return null;
    fail('cc failed:\n${built.stderr}');
  }
  final inFile = File('${dir.path}/in.f64')
    ..writeAsBytesSync(input.buffer.asUint8List());
  final outPath = '${dir.path}/out.f64';
  final ran = Process.runSync(exe, ['-o', outPath, inFile.path]);
  expect(ran.exitCode, 0, reason: 'filter exited ${ran.exitCode}: ${ran.stderr}');
  final bytes = File(outPath).readAsBytesSync();
  return Float64List.view(
      Uint8List.fromList(bytes).buffer, 0, bytes.length ~/ 8);
}

Float64List _noise(int n) {
  final rng = math.Random(4321);
  return Float64List.fromList(
      [for (var i = 0; i < n; i++) rng.nextDouble() * 2 - 1]);
}

void main() {
  late Directory dir;
  setUp(() => dir = Directory.systemTemp.createTempSync('remez_c'));
  tearDown(() => dir.deleteSync(recursive: true));

  group('the text', () {
    test('the FIR source is what the Python writes', () {
      final want = File('test/golden/py_fir.c').readAsStringSync();
      expectSameSource(firCSource(_lowpass().firEffective!, name: 'lp'), want);
    });

    test('the IIR source is what the Python writes', () {
      final want = File('test/golden/py_iir.c').readAsStringSync();
      final c = DesignController();
      c.update(() {
        c.mode = Mode.iir;
        c.approximation = 'elliptic';
        c.wp = ['0.2', '0.3'];
        c.ws = ['0.12', '0.38'];
        c.rp = '0.5';
        c.rs = '40';
        c.response = 'bandpass';
      });
      expectSameSource(iirCSource(c.iirEffective!, name: 'ellip'), want);
    });

    test('the fixed-point note says what was quantized', () {
      final c = _lowpass();
      c.update(() {
        c.arithmetic = Arithmetic.fixed;
        c.wordBits = 12;
      });
      final source = firCSource(c.firEffective!, fixed: c.fixed, name: 'q');
      expect(source, contains('12-bit fixed point, ${c.fixed!.qFormat}'));
      expect(source, contains('static const char *progname = "q";'));
      // The taps written out are the rounded ones, not the ideal ones.
      expect(source, contains(c.firEffective!.h[0].toString().substring(0, 6)));
    });
  });

  group('the program', () {
    test('the FIR filters exactly as the model does', () {
      final c = _lowpass();
      final input = _noise(500);
      final got = _runC(firCSource(c.firEffective!, name: 'lp'), input, dir);
      if (got == null) {
        markTestSkipped('no C compiler');
        return;
      }
      final h = c.firEffective!.h;
      expect(got.length, input.length);
      for (var n = 0; n < input.length; n++) {
        // The same accumulation order the generated loop uses: newest first.
        var acc = 0.0;
        for (var i = 0; i < h.length; i++) {
          acc += h[i] * (n - i >= 0 ? input[n - i] : 0.0);
        }
        expect(got[n], acc, reason: 'sample $n');
      }
    });

    test('the IIR filters exactly as the model does', () {
      final c = _ellipticBandpass();
      final input = _noise(500);
      final got = _runC(iirCSource(c.iirEffective!, name: 'e'), input, dir);
      if (got == null) {
        markTestSkipped('no C compiler');
        return;
      }
      final want = iir.sosFilter(c.iirEffective!.sos, input);
      for (var n = 0; n < input.length; n++) {
        expect(got[n], want[n], reason: 'sample $n');
      }
    });

    test('it filters stdin to stdout, and refuses a terminal', () {
      final c = _lowpass();
      final source = firCSource(c.firEffective!, name: 'lp');
      final src = File('${dir.path}/f.c')..writeAsStringSync(source);
      final exe = '${dir.path}/f';
      if (Process.runSync('cc', ['-O2', '-o', exe, src.path]).exitCode != 0) {
        markTestSkipped('no C compiler');
        return;
      }
      final input = _noise(64);
      File('${dir.path}/in').writeAsBytesSync(input.buffer.asUint8List());
      // No -o, output redirected: the pipeline case.
      final piped = Process.runSync('sh',
          ['-c', '"$exe" < "${dir.path}/in" > "${dir.path}/out"']);
      expect(piped.exitCode, 0, reason: piped.stderr.toString());
      expect(File('${dir.path}/out').lengthSync(), 64 * 8);

      final help = Process.runSync(exe, ['--help']);
      expect(help.exitCode, 0);
      expect(help.stdout, contains('usage:'));

      final bad = Process.runSync(exe, ['--wat']);
      expect(bad.exitCode, 1);
      expect(bad.stderr, contains('unknown option'));
    });
  });
}
