/// The generated SystemVerilog, checked by actually running it.
///
/// Every structure is written out with its self-checking testbench and put
/// through Verilator: first `--lint-only -Wall`, which is stricter than most
/// simulators, then a build and a run. The testbench compares the RTL against
/// `datapath.dart`'s model of the same arithmetic sample for sample, so a pass
/// means the hardware and the plots agree -- which is the only claim worth
/// making about generated RTL.
///
/// The whole matrix is covered: chain, tree and MAC; folded and not; fixed
/// coefficients and a runtime port; symmetric and antisymmetric; and the IIR
/// cascade. If Verilator is not installed the tests skip rather than pass.
library;

import 'dart:io';
import 'dart:math' as math;

import 'package:flutter_test/flutter_test.dart';
import 'package:remez/src/controller.dart';
import 'package:remez/src/rtl_common.dart';
import 'package:remez/src/sv_export.dart';

final bool _haveVerilator =
    Process.runSync('sh', ['-c', 'command -v verilator']).exitCode == 0;

/// A fixed-point FIR to build hardware from.
DesignController _fir({
  int taps = 21,
  int bits = 12,
  bool antisymmetric = false,
}) {
  final c = DesignController();
  c.update(() {
    if (antisymmetric) {
      c.loadPreset('Hilbert transformer');
      c.numtaps = taps;
    } else {
      c.numtaps = taps;
    }
    c.arithmetic = Arithmetic.fixed;
    c.wordBits = bits;
  });
  return c;
}

DesignController _iir() {
  final c = DesignController();
  c.update(() {
    c.mode = Mode.iir;
    c.approximation = 'chebyshev1';
    c.arithmetic = Arithmetic.fixed;
    c.wordBits = 16;
  });
  return c;
}

/// Lint, build and run one design plus its testbench. Returns the run's stdout.
String _verilate(String design, String tb, String name, Directory dir) {
  final d = File('${dir.path}/$name.sv')..writeAsStringSync(design);
  final t = File('${dir.path}/${name}_tb.sv')..writeAsStringSync(tb);

  // --top-module is needed even for the lint: the MAC structure keeps its
  // delay line in a register file, so the library's `_delay` module goes
  // uninstantiated and Verilator reports it as a second candidate top.
  final lint = Process.runSync(
      'verilator',
      [
        '--lint-only', '-Wall', '--timing',
        '--top-module', '${name}_tb',
        d.path, t.path,
      ],
      workingDirectory: dir.path);
  expect(lint.exitCode, 0, reason: 'lint of $name:\n${lint.stderr}');

  final built = Process.runSync(
      'verilator',
      [
        '--binary', '--timing', '-Wno-fatal',
        '--top-module', '${name}_tb',
        '-o', 'sim_$name',
        d.path, t.path,
      ],
      workingDirectory: dir.path);
  expect(built.exitCode, 0, reason: 'build of $name:\n${built.stderr}');

  final ran = Process.runSync('${dir.path}/obj_dir/sim_$name', const [],
      workingDirectory: dir.path);
  final output = '${ran.stdout}${ran.stderr}';
  expect(ran.exitCode, 0, reason: 'run of $name:\n$output');
  return output;
}

/// The one line the two tools legitimately differ on.
String _normalise(String source) =>
    source.replaceAll('// Generated by remez.',
        '// Generated by remez.py.');

/// Line for line against the Python's output, numbers compared as numbers.
///
/// The coefficients are integers and agree exactly; the header quotes a few
/// derived figures -- delta, the pole radius -- that the two designs place a
/// bit apart, so those are compared numerically. Everything else, including
/// every line of RTL, has to match character for character.
void expectSameSource(String got, String want) {
  final a = _normalise(got).split('\n');
  final b = want.split('\n');
  expect(a.length, b.length, reason: 'line count');
  final number = RegExp(r'-?\d+\.?\d*(?:[eE][-+]?\d+)?');
  for (var i = 0; i < b.length; i++) {
    if (a[i] == b[i]) continue;
    expect(a[i].replaceAll(number, 'N'), b[i].replaceAll(number, 'N'),
        reason: 'line ${i + 1}');
    final gotNums = number.allMatches(a[i]).map((m) => double.parse(m[0]!));
    final wantNums = number.allMatches(b[i]).map((m) => double.parse(m[0]!));
    final xs = gotNums.toList();
    final ys = wantNums.toList();
    for (var k = 0; k < ys.length; k++) {
      expect(xs[k], closeTo(ys[k], math.max(ys[k].abs() * 1e-6, 1e-9)),
          reason: 'line ${i + 1}, number ${k + 1}');
    }
  }
}

/// The integers of the block that follows [marker].
List<int> _numbersAfter(String text, String marker) {
  final start = text.indexOf(marker) + marker.length;
  final end = text.indexOf('};', start);
  return RegExp(r'-?\d+')
      .allMatches(text.substring(start, end))
      .map((m) => int.parse(m[0]!))
      .toList();
}

void main() {
  late Directory dir;
  setUp(() => dir = Directory.systemTemp.createTempSync('remez_sv'));
  tearDown(() => dir.deleteSync(recursive: true));

  group('the plan', () {
    test('floating point is refused, with the reason', () {
      final c = DesignController()..design();
      expect(
          () => planFor('fir', c.firResult!, null, const RtlOptions()),
          throwsA(isA<RtlError>().having(
              (e) => e.message, 'message', contains('Fixed point'))));
    });

    test('an IIR cannot be folded or pipelined', () {
      final c = _iir();
      for (final opts in [
        const RtlOptions(folded: true),
        const RtlOptions(structure: 'tree'),
        const RtlOptions(structure: 'mac'),
      ]) {
        expect(
            () => planFor('iir', c.iirResult!, c.fixed, opts),
            throwsA(isA<RtlError>()
                .having((e) => e.message, 'message', contains('cascade'))));
      }
    });

    test('folding is refused when the taps are not symmetric', () {
      final c = _fir();
      // Break the symmetry by hand.
      final broken = c.fixed!.ints..[0] = c.fixed!.ints[0] + 1;
      expect(broken[0], isNot(c.fixed!.ints[c.fixed!.ints.length - 1]));
      expect(
          () => planFor(
              'fir', c.firResult!, c.fixed, const RtlOptions(folded: true)),
          throwsA(isA<RtlError>()
              .having((e) => e.message, 'message', contains('symmetric'))));
    });

    test('folding halves the multipliers and names what each one serves', () {
      final c = _fir(taps: 21);
      final flat = planFor('fir', c.firResult!, c.fixed, const RtlOptions());
      final fold = planFor(
          'fir', c.firResult!, c.fixed, const RtlOptions(folded: true));
      expect(flat.nterms, 21);
      expect(fold.nterms, 11); // ten pairs and the centre tap
      expect(fold.npairs, 10);
      expect(fold.hasCentre, isTrue);
      expect(fold.subtracts, isFalse);
      expect(fold.coeffLabels.first, contains('x[0] + x[20]'));
      expect(fold.coeffLabels.last, contains('centre tap'));
      expect(fold.resources.multipliers, 11);
      // The taps themselves are still all there, for the model.
      expect(fold.taps, hasLength(21));
    });

    test('an antisymmetric fold subtracts and drops the centre tap', () {
      final c = _fir(taps: 21, antisymmetric: true);
      final plan = planFor(
          'fir', c.firResult!, c.fixed, const RtlOptions(folded: true));
      expect(plan.subtracts, isTrue);
      expect(plan.hasCentre, isFalse);
      expect(plan.nterms, 10);
      expect(plan.coeffLabels.first, contains('x[0] - x[20]'));
    });

    test('latency is what the header claims', () {
      final c = _fir(taps: 21);
      expect(planFor('fir', c.firResult!, c.fixed, const RtlOptions()).latency,
          1);
      expect(
          planFor('fir', c.firResult!, c.fixed,
                  const RtlOptions(structure: 'tree'))
              .latency,
          1 + 5); // ceil(log2(21)) levels
      expect(
          planFor('fir', c.firResult!, c.fixed,
                  const RtlOptions(structure: 'mac'))
              .latency,
          23); // one clock per term, plus two
      final ir = _iir();
      expect(
          planFor('iir', ir.iirResult!, ir.fixed, const RtlOptions()).latency,
          1);
    });
  });

  group('against the Python output', () {
    test('the FIR chain RTL is what the Python writes', () {
      final c = _fir(taps: 15, bits: 10);
      const opts = RtlOptions(name: 'dut', headroom: 2);
      final plan = planFor('fir', c.firResult!, c.fixed, opts);
      expectSameSource(
          renderFir(plan), File('test/golden/py_fir.sv').readAsStringSync());
    });

    test('and so is its testbench, vectors included', () {
      // The stimulus is generated, so it is pinned to the Python's list; the
      // expected outputs then come from this port's own datapath model, and
      // matching them means the two models agree sample for sample.
      final c = _fir(taps: 15, bits: 10);
      const opts = RtlOptions(name: 'dut', headroom: 2);
      final plan = planFor('fir', c.firResult!, c.fixed, opts);
      final want = File('test/golden/py_fir_tb.sv').readAsStringSync();
      final stim = _numbersAfter(want, "localparam longint STIM   [0:NS-1] = '{");
      expectSameSource(testbenchForPlan(plan, samples: stim), want);
    });

    test('the IIR cascade RTL is what the Python writes', () {
      final c = DesignController();
      c.update(() {
        c.mode = Mode.iir;
        c.approximation = 'chebyshev1';
        c.wp = ['0.2', '0.4'];
        c.ws = ['0.3', '0.45'];
        c.rp = '0.5';
        c.rs = '40';
        c.arithmetic = Arithmetic.fixed;
        c.wordBits = 16;
      });
      const opts = RtlOptions(name: 'biq', headroom: 2);
      final plan = planFor('iir', c.iirResult!, c.fixed, opts);
      expectSameSource(
          renderIir(plan), File('test/golden/py_iir.sv').readAsStringSync());
    });
  });

  group('Verilator', () {
    setUp(() {
      if (!_haveVerilator) markTestSkipped('verilator is not installed');
    });

    for (final structure in ['chain', 'tree', 'mac']) {
      for (final folded in [false, true]) {
        for (final fixedCoeffs in [true, false]) {
          final label =
              '$structure${folded ? ' folded' : ''}, '
              '${fixedCoeffs ? 'constant' : 'runtime'} coefficients';
          test('a FIR builds and matches the model: $label', () {
            if (!_haveVerilator) return;
            final c = _fir(taps: 15, bits: 10);
            final opts = RtlOptions(
                name: 'f_${structure}_${folded ? 'fold' : 'flat'}_'
                    '${fixedCoeffs ? 'k' : 'p'}',
                structure: structure,
                folded: folded,
                fixedCoeffs: fixedCoeffs);
            final plan = planFor('fir', c.firResult!, c.fixed, opts);
            final out = _verilate(renderFir(plan), testbenchForPlan(plan),
                plan.name, dir);
            expect(out, contains('PASS'));
          }, timeout: const Timeout(Duration(minutes: 3)));
        }
      }
    }

    test('an antisymmetric folded FIR builds and matches', () {
      if (!_haveVerilator) return;
      final c = _fir(taps: 15, bits: 10, antisymmetric: true);
      const opts = RtlOptions(name: 'anti', folded: true);
      final plan = planFor('fir', c.firResult!, c.fixed, opts);
      expect(plan.subtracts, isTrue);
      expect(_verilate(renderFir(plan), testbenchForPlan(plan), 'anti', dir),
          contains('PASS'));
    }, timeout: const Timeout(Duration(minutes: 3)));

    for (final fixedCoeffs in [true, false]) {
      test('the IIR cascade builds and matches the model, '
          '${fixedCoeffs ? 'constant' : 'runtime'} coefficients', () {
        if (!_haveVerilator) return;
        final c = _iir();
        final opts = RtlOptions(
            name: 'biq_${fixedCoeffs ? 'k' : 'p'}', fixedCoeffs: fixedCoeffs);
        final plan = planFor('iir', c.iirResult!, c.fixed, opts);
        expect(_verilate(renderIir(plan), testbenchForPlan(plan), plan.name,
            dir), contains('PASS'));
      }, timeout: const Timeout(Duration(minutes: 3)));
    }
  });
}
