/// The generated VHDL, checked by actually running it.
///
/// The same matrix the SystemVerilog back-end is put through, and against the
/// same model: every structure is written out with its self-checking testbench,
/// analysed with `ghdl -a --std=93`, elaborated and run. The testbench carries
/// the expected output of every sample from `datapath.dart`, so a pass means
/// the VHDL, the SystemVerilog and the plots all describe one filter.
///
/// If ghdl is not installed the tests skip rather than pass.
library;

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:remez/src/controller.dart';
import 'package:remez/src/rtl_common.dart';
import 'package:remez/src/vhdl_export.dart' as vhdl;

final bool _haveGhdl =
    Process.runSync('sh', ['-c', 'command -v ghdl']).exitCode == 0;

DesignController _fir({
  int taps = 15,
  int bits = 10,
  bool antisymmetric = false,
}) {
  final c = DesignController();
  c.update(() {
    if (antisymmetric) c.loadPreset('Hilbert transformer');
    c.numtaps = taps;
    c.arithmetic = Arithmetic.fixed;
    c.wordBits = bits;
  });
  return c;
}

DesignController _iir({int bits = 16}) {
  final c = DesignController();
  c.update(() {
    c.mode = Mode.iir;
    c.approximation = 'chebyshev1';
    c.arithmetic = Arithmetic.fixed;
    c.wordBits = bits;
  });
  return c;
}

/// Analyse, elaborate and run one design plus its testbench.
String _ghdl(String design, String tb, String name, Directory dir) {
  final d = File('${dir.path}/$name.vhd')..writeAsStringSync(design);
  final t = File('${dir.path}/${name}_tb.vhd')..writeAsStringSync(tb);

  final analysed = Process.runSync('ghdl', ['-a', '--std=93', d.path, t.path],
      workingDirectory: dir.path);
  expect(analysed.exitCode, 0,
      reason: 'analysis of $name:\n${analysed.stdout}${analysed.stderr}');

  final elaborated = Process.runSync('ghdl', ['-e', '--std=93', '${name}_tb'],
      workingDirectory: dir.path);
  expect(elaborated.exitCode, 0,
      reason: 'elaboration of $name:\n${elaborated.stdout}${elaborated.stderr}');

  final ran = Process.runSync(
      'ghdl', ['-r', '--std=93', '${name}_tb', '--assert-level=error'],
      workingDirectory: dir.path);
  final output = '${ran.stdout}${ran.stderr}';
  expect(ran.exitCode, 0, reason: 'run of $name:\n$output');
  return output;
}

/// The one line the two tools legitimately differ on.
String _normalise(String source) => source.replaceAll(
    '-- Generated by remez.', '-- Generated by remez.py.');

final RegExp _number = RegExp(r'-?\d+\.?\d*(?:[eE][-+]?\d+)?');

/// Line for line against the Python's output, numbers compared as numbers.
///
/// The coefficients are integers and agree exactly; the header quotes a few
/// derived figures -- delta, the pole radius -- that the two designs place a
/// bit apart, so those are compared numerically. Every line of VHDL has to
/// match character for character.
void expectSameSource(String got, String want) {
  final a = _normalise(got).split('\n');
  final b = want.split('\n');
  expect(a.length, b.length, reason: 'line count');
  for (var i = 0; i < b.length; i++) {
    if (a[i] == b[i]) continue;
    expect(a[i].replaceAll(_number, 'N'), b[i].replaceAll(_number, 'N'),
        reason: 'line ${i + 1}');
    final xs = _number.allMatches(a[i]).map((m) => double.parse(m[0]!)).toList();
    final ys = _number.allMatches(b[i]).map((m) => double.parse(m[0]!)).toList();
    for (var k = 0; k < ys.length; k++) {
      final tol = ys[k].abs() * 1e-6;
      expect(xs[k], closeTo(ys[k], tol > 1e-9 ? tol : 1e-9),
          reason: 'line ${i + 1}, number ${k + 1}');
    }
  }
}

/// The integers of the block that follows [marker].
List<int> _numbersAfter(String text, String marker) {
  final start = text.indexOf(marker) + marker.length;
  final end = text.indexOf(');', start);
  return RegExp(r'-?\d+')
      .allMatches(text.substring(start, end))
      .map((m) => int.parse(m[0]!))
      .toList();
}

void main() {
  late Directory dir;
  setUp(() => dir = Directory.systemTemp.createTempSync('remez_vhdl'));
  tearDown(() => dir.deleteSync(recursive: true));

  test('a coefficient too wide for an integer generic is refused', () {
    // VHDL-93 carries them as integers, so 31 bits is the ceiling. The error
    // has to say so and point at the back-end that has no such limit.
    final c = _fir(bits: 32);
    expect(
        () => vhdl.firSource(c.firResult!, c.fixed, const RtlOptions()),
        throwsA(isA<RtlError>()
            .having((e) => e.message, 'message', contains('31 bits'))
            .having((e) => e.message, 'message', contains('SystemVerilog'))));

    // And one that fits does not complain.
    final ok = _fir(bits: 31);
    expect(() => vhdl.firSource(ok.firResult!, ok.fixed, const RtlOptions()),
        returnsNormally);
  });

  group('against the Python output', () {
    test('the FIR chain is what the Python writes', () {
      final c = _fir();
      const opts = RtlOptions(name: 'dut', headroom: 2);
      expectSameSource(vhdl.renderFir(planFor('fir', c.firResult!, c.fixed, opts)),
          File('test/golden/py_fir.vhd').readAsStringSync());
    });

    test('and the hardest structure it has: a folded MAC on a coefficient port',
        () {
      final c = _fir();
      const opts = RtlOptions(
          name: 'dut',
          headroom: 2,
          structure: 'mac',
          folded: true,
          fixedCoeffs: false);
      expectSameSource(vhdl.renderFir(planFor('fir', c.firResult!, c.fixed, opts)),
          File('test/golden/py_mac.vhd').readAsStringSync());
    });

    test('and so is the testbench, vectors included', () {
      // The stimulus is generated, so it is pinned to the Python's list; the
      // expected outputs then come from this port's own datapath model, and
      // matching them means the two models agree sample for sample.
      final c = _fir();
      const opts = RtlOptions(name: 'dut', headroom: 2);
      final plan = planFor('fir', c.firResult!, c.fixed, opts);
      final want = File('test/golden/py_fir_tb.vhd').readAsStringSync();
      final stim = _numbersAfter(
          want, 'constant STIM : int_array_t(0 to NSAMPLES-1) := (');
      expectSameSource(vhdl.testbenchForPlan(plan, samples: stim), want);
    });

    test('the IIR cascade is what the Python writes', () {
      final c = DesignController();
      c.update(() {
        c.mode = Mode.iir;
        c.approximation = 'chebyshev1';
        c.wp = ['0.2', '0.4'];
        c.ws = ['0.3', '0.45'];
        c.rp = '0.5';
        c.rs = '40';
        c.arithmetic = Arithmetic.fixed;
        c.wordBits = 16;
      });
      const opts = RtlOptions(name: 'biq', headroom: 2);
      expectSameSource(vhdl.renderIir(planFor('iir', c.iirResult!, c.fixed, opts)),
          File('test/golden/py_iir.vhd').readAsStringSync());
    });
  });

  group('ghdl', () {
    setUp(() {
      if (!_haveGhdl) markTestSkipped('ghdl is not installed');
    });

    for (final structure in ['chain', 'tree', 'mac']) {
      for (final folded in [false, true]) {
        for (final fixedCoeffs in [true, false]) {
          final label = '$structure${folded ? ' folded' : ''}, '
              '${fixedCoeffs ? 'constant' : 'runtime'} coefficients';
          test('a FIR analyses, runs and matches the model: $label', () {
            if (!_haveGhdl) return;
            final c = _fir();
            final opts = RtlOptions(
                name: 'v_${structure}_${folded ? 'fold' : 'flat'}_'
                    '${fixedCoeffs ? 'k' : 'p'}',
                structure: structure,
                folded: folded,
                fixedCoeffs: fixedCoeffs);
            final plan = planFor('fir', c.firResult!, c.fixed, opts);
            expect(
                _ghdl(vhdl.renderFir(plan), vhdl.testbenchForPlan(plan),
                    plan.name, dir),
                contains('PASS'));
          }, timeout: const Timeout(Duration(minutes: 3)));
        }
      }
    }

    test('an antisymmetric folded FIR analyses, runs and matches', () {
      if (!_haveGhdl) return;
      final c = _fir(antisymmetric: true);
      const opts = RtlOptions(name: 'vanti', folded: true);
      final plan = planFor('fir', c.firResult!, c.fixed, opts);
      expect(plan.subtracts, isTrue);
      expect(
          _ghdl(vhdl.renderFir(plan), vhdl.testbenchForPlan(plan), 'vanti', dir),
          contains('PASS'));
    }, timeout: const Timeout(Duration(minutes: 3)));

    for (final fixedCoeffs in [true, false]) {
      test(
          'the IIR cascade analyses, runs and matches the model, '
          '${fixedCoeffs ? 'constant' : 'runtime'} coefficients', () {
        if (!_haveGhdl) return;
        final c = _iir();
        final opts = RtlOptions(
            name: 'vbiq_${fixedCoeffs ? 'k' : 'p'}', fixedCoeffs: fixedCoeffs);
        final plan = planFor('iir', c.iirResult!, c.fixed, opts);
        expect(
            _ghdl(vhdl.renderIir(plan), vhdl.testbenchForPlan(plan), plan.name,
                dir),
            contains('PASS'));
      }, timeout: const Timeout(Duration(minutes: 3)));
    }
  });
}
