/*
 * Elliptic bandpass IIR filter, order 7
 * sample rate 32000, passband edges 200, 400, stopband edges 150, 450
 * 0.5 dB passband ripple, 60 dB stopband attenuation (achieved 0.5 dB / 60 dB)
 * max |pole| = 0.9995943399
 * double precision coefficients
 *
 * Cascade of 7 biquads, each transposed direct form II.
 * Generated by remez.py.
 *
 *     t_ctx ctx;
 *     if (init_filter(&ctx) != 0) ... out of memory ...
 *     for (...) y = process_sample(x, &ctx);
 *     free_filter(&ctx);
 *
 * Compile with -DFILTER_MAIN for a stand-alone program that filters
 * whitespace-separated doubles from stdin to stdout.
 */

#include <stdlib.h>

#define FILTER_SECTIONS 7

/* one row per section: b0, b1, b2, a1, a2   (a0 is 1) */
static const double filter_sos[FILTER_SECTIONS][5] = {
    {  0.00012682865217991993, -0.00025348999477574829,  0.00012682865217991996, -1.9837194780591287,  0.98678295336832167 },
    {  1, -1.9927950966889323,  1, -1.9836027006163013,  0.98818663396578688 },
    {  1, -1.9988287395542437,  1.0000000000000002, -1.9900279697912013,  0.99208196294799322 },
    {  1, -1.9918867403586287,  1.0000000000000002, -1.9883136732414102,  0.99402223514540666 },
    {  1, -1.9992989769837042,  0.99999999999999967, -1.9951169933681072,  0.99677477670106196 },
    {  1, -1.9864612994255715,  0.99999999999999978, -1.9921931172124012,  0.99837415324907763 },
    {  1,  0, -1, -1.9976527138183038,  0.99918884437846378 },
};

typedef struct {
    double *state;      /* two delay elements per section */
    size_t  sections;
} t_ctx;

/* Allocates the filter state, zeroed.  Returns 0, or -1 if out of
   memory, in which case ctx is left safe to pass to free_filter. */
int init_filter(t_ctx *ctx)
{
    ctx->sections = FILTER_SECTIONS;
    ctx->state = (double *) calloc(2 * FILTER_SECTIONS,
                                   sizeof *ctx->state);
    return ctx->state ? 0 : -1;
}

void free_filter(t_ctx *ctx)
{
    free(ctx->state);
    ctx->state = NULL;
    ctx->sections = 0;
}

/*  y     = b0*x + s0
    s0'   = b1*x - a1*y + s1
    s1'   = b2*x - a2*y            , section by section  */
double process_sample(double sample, t_ctx *ctx)
{
    size_t i;

    for (i = 0; i < ctx->sections; i++) {
        const double *c = filter_sos[i];
        double *s = ctx->state + 2 * i;
        double out = c[0] * sample + s[0];

        s[0] = c[1] * sample - c[3] * out + s[1];
        s[1] = c[2] * sample - c[4] * out;
        sample = out;
    }
    return sample;
}

#ifdef FILTER_MAIN
#include <stdio.h>

int main(void)
{
    t_ctx ctx;
    double x;

    if (init_filter(&ctx) != 0) {
        fprintf(stderr, "init_filter: out of memory\n");
        return 1;
    }
    while (scanf("%lf", &x) == 1)
        printf("%.17g\n", process_sample(x, &ctx));
    free_filter(&ctx);
    return 0;
}
#endif
