/*
 * Parks-McClellan FIR filter, type 1 (symmetric), N = 41
 * sample rate 1, bands 0–0.2, 0.25–0.5
 * weighted delta = 0.02876629731
 * double precision coefficients
 *
 * Direct form: a tapped delay line into one accumulator.
 * Generated by remez.py.
 *
 * As a library:
 *
 *     t_ctx ctx;
 *     if (init_filter(&ctx) != 0) ... out of memory ...
 *     for (...) y = process_sample(x, &ctx);
 *     free_filter(&ctx);
 *
 * As a program, which is what it builds as by default:
 *
 *     cc -O2 -o filter this.c
 *     ./filter [-o outfile] [infile]
 *
 * It reads and writes raw 64 bit float samples in native byte
 * order, stdin to stdout unless told otherwise.  Compile with
 * -DFILTER_NO_MAIN to leave main out and link it into something
 * else instead.
 */

#include <stdlib.h>

#define FILTER_TAPS 41

static const double filter_taps[FILTER_TAPS] = {
     0.0035407331446868362,
     0.0012834005762769555,
    -0.007037704548036052,
    -0.012111852934689941,
    -0.0036452856782416012,
     0.0090956623512756154,
     0.0056837142498315099,
    -0.011634930542055843,
    -0.013857521600856163,
     0.0092487454932715339,
     0.022790056265592818,
    -0.0028266257335476867,
    -0.033030136907111235,
    -0.010760877222981531,
     0.04289175676506897,
     0.035777422919688759,
    -0.051194231341862878,
    -0.088023908445945875,
     0.056716811387308726,
     0.31204223177823986,
     0.44133878273738059,
     0.31204223177823986,
     0.056716811387308726,
    -0.088023908445945875,
    -0.051194231341862878,
     0.035777422919688759,
     0.04289175676506897,
    -0.010760877222981531,
    -0.033030136907111235,
    -0.0028266257335476867,
     0.022790056265592818,
     0.0092487454932715339,
    -0.013857521600856163,
    -0.011634930542055843,
     0.0056837142498315099,
     0.0090956623512756154,
    -0.0036452856782416012,
    -0.012111852934689941,
    -0.007037704548036052,
     0.0012834005762769555,
     0.0035407331446868362,
};

typedef struct {
    double *state;      /* circular delay line, FILTER_TAPS long */
    size_t  taps;
    size_t  pos;        /* where the next sample goes */
} t_ctx;

/* Allocates the delay line, zeroed.  Returns 0, or -1 if out of
   memory, in which case ctx is left safe to pass to free_filter. */
int init_filter(t_ctx *ctx)
{
    ctx->taps = FILTER_TAPS;
    ctx->pos = 0;
    ctx->state = (double *) calloc(FILTER_TAPS, sizeof *ctx->state);
    return ctx->state ? 0 : -1;
}

void free_filter(t_ctx *ctx)
{
    free(ctx->state);
    ctx->state = NULL;
    ctx->taps = ctx->pos = 0;
}

/*  y[n] = sum_i h[i] * x[n-i]  */
double process_sample(double sample, t_ctx *ctx)
{
    double acc = 0.0;
    size_t i, k;

    ctx->state[ctx->pos] = sample;
    k = ctx->pos;
    for (i = 0; i < ctx->taps; i++) {
        acc += filter_taps[i] * ctx->state[k];
        k = k ? k - 1 : ctx->taps - 1;
    }
    ctx->pos = ctx->pos + 1 == ctx->taps ? 0 : ctx->pos + 1;
    return acc;
}

#ifndef FILTER_NO_MAIN
#include <errno.h>
#include <stdio.h>
#include <string.h>

#ifdef _WIN32
#include <fcntl.h>
#include <io.h>
#else
#include <unistd.h>
#endif

/* Samples carried per read; the buffer is doubles so it stays aligned. */
#define IO_SAMPLES 4096

static const char *progname = "lp";

static void usage(FILE *out)
{
    fprintf(out, "usage: %s [-o outfile] [infile]\n", progname);
    fprintf(out, "  Filters raw 64 bit float PCM samples (native byte order).\n");
    fprintf(out, "  infile defaults to stdin, output defaults to stdout.\n");
}

/* Filters in to out a block at a time.  Returns 0, or -1 after reporting
   an I/O error.  A trailing fragment shorter than one sample is reported
   and dropped. */
static int filter_stream(FILE *in, FILE *out, t_ctx *ctx)
{
    double buf[IO_SAMPLES];
    unsigned char *bytes = (unsigned char *) buf;
    size_t leftover = 0;
    size_t got;

    while ((got = fread(bytes + leftover, 1, sizeof buf - leftover, in)) > 0) {
        size_t total = leftover + got;
        size_t count = total / sizeof(double);
        size_t i;

        for (i = 0; i < count; i++)
            buf[i] = process_sample(buf[i], ctx);

        if (count && fwrite(buf, sizeof(double), count, out) != count) {
            fprintf(stderr, "%s: write failed: %s\n", progname, strerror(errno));
            return -1;
        }

        /* Carry any bytes that did not complete a sample into the next read. */
        leftover = total - count * sizeof(double);
        if (leftover)
            memmove(bytes, bytes + count * sizeof(double), leftover);
    }

    if (ferror(in)) {
        fprintf(stderr, "%s: read failed: %s\n", progname, strerror(errno));
        return -1;
    }
    if (leftover)
        fprintf(stderr, "%s: ignoring %lu trailing byte(s), not a whole sample\n",
                progname, (unsigned long) leftover);

    return 0;
}

int main(int argc, char **argv)
{
    const char *in_path = NULL;
    const char *out_path = NULL;
    FILE *in = stdin;
    FILE *out = stdout;
    t_ctx ctx;
    int status = 0;
    int i;

    if (argc > 0 && argv[0] && argv[0][0])
        progname = argv[0];

    for (i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-o") == 0) {
            if (++i == argc) {
                fprintf(stderr, "%s: -o needs a filename\n", progname);
                return 1;
            }
            out_path = argv[i];
        } else if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0) {
            usage(stdout);
            return 0;
        } else if (strcmp(argv[i], "-") == 0) {
            in_path = NULL;             /* explicit stdin */
        } else if (argv[i][0] == '-' && argv[i][1]) {
            fprintf(stderr, "%s: unknown option: %s\n", progname, argv[i]);
            usage(stderr);
            return 1;
        } else if (in_path == NULL) {
            in_path = argv[i];
        } else {
            fprintf(stderr, "%s: only one input file may be given\n", progname);
            return 1;
        }
    }

    if (in_path) {
        in = fopen(in_path, "rb");
        if (!in) {
            fprintf(stderr, "%s: %s: %s\n", progname, in_path, strerror(errno));
            return 1;
        }
    }

    if (out_path) {
        out = fopen(out_path, "wb");
        if (!out) {
            fprintf(stderr, "%s: %s: %s\n", progname, out_path, strerror(errno));
            if (in != stdin)
                fclose(in);
            return 1;
        }
    }

#ifdef _WIN32
    if (in == stdin)
        _setmode(_fileno(stdin), _O_BINARY);
    if (out == stdout)
        _setmode(_fileno(stdout), _O_BINARY);
#else
    /* Raw samples down a terminal are noise, and usually a forgotten -o. */
    if (out == stdout && isatty(fileno(stdout))) {
        fprintf(stderr, "%s: refusing to write binary samples to a terminal; "
                        "use -o or redirect\n", progname);
        if (in != stdin)
            fclose(in);
        return 1;
    }
#endif

    if (init_filter(&ctx) != 0) {
        fprintf(stderr, "%s: init_filter: out of memory\n", progname);
        status = 1;
    } else {
        if (filter_stream(in, out, &ctx) != 0)
            status = 1;
        free_filter(&ctx);
    }

    if (in != stdin)
        fclose(in);
    if (fflush(out) != 0 || (out != stdout && fclose(out) != 0)) {
        fprintf(stderr, "%s: %s: %s\n", progname,
                out_path ? out_path : "stdout", strerror(errno));
        status = 1;
    }

    return status;
}
#endif
