-- =====================================================================
-- dut: Parks-McClellan FIR, type 1 (symmetric), N = 15
--
-- sample rate 1, bands 0-0.2, 0.25-0.5
-- weighted delta = 0.27933 as designed
-- Structure: accumulator chain (one adder per tap, shortest area, longest path).
--
-- Coefficients  10 bits, Q-1.10   (value = integer * 2^-10)
-- Datapath      12 bits = 10 + 2 headroom, Q1.10
--               unity is 1024, range [-2, 1.99902]
-- Products are exact, then rounded to nearest and saturated; adds
-- saturate.  Headroom is what keeps the adders off their limits.
--
-- Costs         15 multipliers, 14 adders, 14 delays
--
-- clk / resetn        synchronous, active-low reset
-- din, din_strb       one sample per strobe
-- dout, dout_strb     the result, 1 clock after din_strb
--
-- Coefficients are elaboration-time generics, so synthesis can
-- specialise each multiplier.  There is no coefficient port.
--
-- Generated by remez.py.  Analyse it with, for example:
--     $ ghdl -a --std=93 <this file>
-- =====================================================================


-- ---------------------------------------------------------------------
-- Clamp a wide signed value into a narrow one.  Overflow is detected by
-- looking at the bits above the target's sign bit: if they all match it,
-- the value fits.  That avoids computing the limits as integers, which
-- would themselves overflow for a wide datapath.
-- ---------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity dut_sat is
    generic (
        WIN  : positive := 32;
        WOUT : positive := 16);
    port (
        din  : in  signed(WIN-1 downto 0);
        dout : out signed(WOUT-1 downto 0));
end entity dut_sat;

architecture rtl of dut_sat is
    -- 0111..1 and 1000..0.  Built by shifting rather than as an
    -- aggregate, because a choice that depends on a generic is not
    -- locally static and so cannot be mixed with 'others'.
    constant HI : signed(WOUT-1 downto 0) := to_signed(-1, WOUT) srl 1;
    constant LO : signed(WOUT-1 downto 0) := not HI;
begin
    process (din)
        variable top : signed(WIN-WOUT downto 0);
    begin
        top := din(WIN-1 downto WOUT-1);
        if top = to_signed(0, top'length) or
           top = to_signed(-1, top'length) then
            dout <= din(WOUT-1 downto 0);
        elsif din(WIN-1) = '0' then
            dout <= HI;
        else
            dout <= LO;
        end if;
    end process;
end architecture rtl;


-- ---------------------------------------------------------------------
-- One coefficient multiply.
--
-- The product is formed exactly in WDATA+WCOEF bits, which leaves it with
-- 2*FRAC fractional bits; half an LSB is added and it is shifted back
-- down to FRAC, then saturated into the datapath width.  With FIXED true
-- the coefficient is a generic, so synthesis can fold the multiply down
-- to shifts and adds; otherwise it comes from the port.  NEG negates it,
-- which is how the feedback taps of a biquad are subtracted without a
-- separate subtractor.
-- ---------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity dut_mul is
    generic (
        WDATA : positive := 16;
        WIN   : positive := 16;   -- wider for a folded pre-add
        WCOEF : positive := 12;
        FRAC  : natural  := 11;
        FIXED : boolean  := true;
        NEG   : boolean  := false;
        COEF_FIXED : integer := 0);   -- COEF would clash with the port
    port (
        coef : in  signed(WCOEF-1 downto 0);
        din  : in  signed(WIN-1 downto 0);
        dout : out signed(WDATA-1 downto 0));
end entity dut_mul;

architecture rtl of dut_mul is
    constant WPROD : positive := WIN + WCOEF;
    constant CMAX  : integer  := 2**(WCOEF-1) - 1;
    constant CMIN  : integer  := -(2**(WCOEF-1));
    -- Saturating negate at elaboration, for the fixed case.  A
    -- conditional expression in a constant would need VHDL-2019, so this
    -- is a function.
    function chosen (v : integer; flip : boolean) return integer is
    begin
        if not flip then
            return v;
        elsif -v > CMAX then
            return CMAX;
        elsif -v < CMIN then
            return CMIN;
        else
            return -v;
        end if;
    end function chosen;
    constant CFIX : integer := chosen(COEF_FIXED, NEG);

    signal c       : signed(WCOEF-1 downto 0);
    signal rounded : signed(WPROD-1 downto 0);
begin
    coefficient : process (coef)
    begin
        if FIXED then
            c <= to_signed(CFIX, WCOEF);
        elsif NEG then
            if coef = to_signed(CMIN, WCOEF) then
                c <= to_signed(CMAX, WCOEF);
            else
                c <= -coef;
            end if;
        else
            c <= coef;
        end if;
    end process coefficient;

    product : process (din, c)
        variable prod : signed(WPROD-1 downto 0);
        variable half : signed(WPROD-1 downto 0);
    begin
        prod := din * c;
        if FRAC > 0 then
            half    := to_signed(0, WPROD);
            half(FRAC-1) := '1';
            rounded <= shift_right(prod + half, FRAC);
        else
            rounded <= prod;
        end if;
    end process product;

    u_sat : entity work.dut_sat
        generic map (WIN => WPROD, WOUT => WDATA)
        port map (din => rounded, dout => dout);
end architecture rtl;


-- ---------------------------------------------------------------------
-- One datapath-width add, saturating rather than wrapping: a filter that
-- clips is bad, one that wraps is unrecognisable.  SUB subtracts, which
-- is what the pre-adders of a folded antisymmetric filter do.
-- ---------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity dut_add is
    generic (
        WDATA : positive := 16;
        SUB   : boolean  := false);
    port (
        a   : in  signed(WDATA-1 downto 0);
        b   : in  signed(WDATA-1 downto 0);
        sum : out signed(WDATA-1 downto 0));
end entity dut_add;

architecture rtl of dut_add is
    signal full : signed(WDATA downto 0);
begin
    process (a, b)
    begin
        if SUB then
            full <= resize(a, WDATA+1) - resize(b, WDATA+1);
        else
            full <= resize(a, WDATA+1) + resize(b, WDATA+1);
        end if;
    end process;

    u_sat : entity work.dut_sat
        generic map (WIN => WDATA+1, WOUT => WDATA)
        port map (din => full, dout => sum);
end architecture rtl;


-- ---------------------------------------------------------------------
-- One register.  It advances only when enabled, which makes it both the
-- unit delay of the filter (enabled once per input sample) and the
-- pipeline register between adder-tree levels.
-- ---------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity dut_delay is
    generic (
        WDATA : positive := 16);
    port (
        clk    : in  std_logic;
        resetn : in  std_logic;
        en     : in  std_logic;
        d      : in  signed(WDATA-1 downto 0);
        q      : out signed(WDATA-1 downto 0));
end entity dut_delay;

architecture rtl of dut_delay is
begin
    process (clk)
    begin
        if rising_edge(clk) then
            if resetn = '0' then
                q <= (others => '0');
            elsif en = '1' then
                q <= d;
            end if;
        end if;
    end process;
end architecture rtl;


-- ---------------------------------------------------------------------
-- dut: the filter itself.
-- ---------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity dut is
    generic (
        -- These describe the filter that was generated: the
        -- coefficients below are stored in this format, so overriding
        -- them would leave the two disagreeing.  LATENCY is here to be
        -- read by whatever instantiates this.
        NTAPS    : positive := 15;
        NTERM    : positive := 15;
        NCOEF    : positive := 15;
        WCOEF    : positive := 10;
        FRAC     : natural  := 10;
        HEADROOM : natural  := 2;
        LATENCY  : positive := 1;
        WDATA    : positive := 12);
    port (
        clk       : in  std_logic;
        resetn    : in  std_logic;
        din       : in  signed(WDATA-1 downto 0);
        din_strb  : in  std_logic;
        dout      : out signed(WDATA-1 downto 0);
        dout_strb : out std_logic);
end entity dut;

architecture rtl of dut is
    constant WTERM : positive := WDATA + 0;

    type data_array_t is array (natural range <>) of signed(WDATA-1 downto 0);
    type term_array_t is array (natural range <>) of signed(WTERM-1 downto 0);
    type coef_array_t is array (natural range <>) of integer;

    -- The impulse response, as stored integers.
    constant COEF : coef_array_t(0 to NCOEF-1) := (
        54, 94, 50, -55, -94, 62, 318, 451,
        318, 62, -94, -55, 50, 94, 54
    );

    signal x    : data_array_t(0 to NTAPS-1);
    signal term : term_array_t(0 to NTERM-1);
    signal prod : data_array_t(0 to NTERM-1);
    signal acc  : data_array_t(0 to NTERM-1);
begin
    -- x(0) is this cycle's sample; x(k) is it delayed by k strobes.
    x(0) <= din;

    g_delay : for k in 1 to NTAPS-1 generate
        u_z : entity work.dut_delay
            generic map (WDATA => WDATA)
            port map (clk => clk, resetn => resetn, en => din_strb,
                      d => x(k-1), q => x(k));
    end generate g_delay;

    g_term : for k in 0 to NTERM-1 generate
        term(k) <= x(k);
    end generate g_term;

    g_mul : for k in 0 to NTERM-1 generate
        u_mul : entity work.dut_mul
            generic map (WDATA => WDATA, WIN => WTERM, WCOEF => WCOEF, FRAC => FRAC,
                         FIXED => true, NEG => false,
                         COEF_FIXED => COEF(k))
            port map (coef => to_signed(0, WCOEF),
                      din => term(k), dout => prod(k));
    end generate g_mul;

    -- Sum the products along a chain of adders, in tap order.
    acc(0) <= prod(0);

    g_sum : for k in 1 to NTERM-1 generate
        u_add : entity work.dut_add
            generic map (WDATA => WDATA)
            port map (a => acc(k-1), b => prod(k), sum => acc(k));
    end generate g_sum;

    output : process (clk)
    begin
        if rising_edge(clk) then
            if resetn = '0' then
                dout      <= (others => '0');
                dout_strb <= '0';
            else
                if din_strb = '1' then
                    dout <= acc(NTERM-1);
                end if;
                dout_strb <= din_strb;
            end if;
        end if;
    end process output;
end architecture rtl;
