// =====================================================================
// dut: Parks-McClellan FIR, type 1 (symmetric), N = 15
//
// sample rate 1, bands 0-0.2, 0.25-0.5
// weighted delta = 0.27933 as designed
// Structure: accumulator chain (one adder per tap, shortest area, longest path).
//
// Coefficients  10 bits, Q-1.10   (value = integer * 2^-10)
// Datapath      12 bits = 10 + 2 headroom, Q1.10
//               unity is 1024, range [-2, 1.99902]
// Products are exact, then rounded to nearest and saturated; adds
// saturate.  Headroom is what keeps the adders off their limits.
//
// Costs         15 multipliers, 14 adders, 14 delays
//
// clk / resetn        synchronous, active-low reset
// din, din_strb       one sample per strobe
// dout, dout_strb     the result, 1 clock after din_strb
//
// Coefficients are elaboration-time parameters, so synthesis can
// specialise each multiplier.  There is no coefficient port.
//
// Generated by remez.py.  Lint it with, for example:
//     $ verilator --lint-only -Wall <this file>
// =====================================================================

`default_nettype none

// Everything the filter needs is in this one file, so the checker's
// one-module-per-file rule does not apply to it.
/* verilator lint_off DECLFILENAME */


// ---------------------------------------------------------------------
// One coefficient multiply.
//
// The product is formed exactly in WDATA+WCOEF bits, which leaves it
// with 2*FRAC fractional bits; half an LSB is added and it is shifted
// back down to FRAC, then saturated into the datapath width.  With
// FIXED set the coefficient is a parameter, so synthesis can fold the
// multiply down to shifts and adds; otherwise it comes from the port.
// NEG negates the coefficient, which is how the feedback taps of a
// biquad are subtracted without a separate subtractor.
// ---------------------------------------------------------------------
module dut_mul #(
    parameter int     WDATA = 16,
    parameter int     WIN   = WDATA,   // wider for a folded pre-add
    parameter int     WCOEF = 12,
    parameter int     FRAC  = 11,
    parameter bit     FIXED = 1'b1,
    parameter bit     NEG   = 1'b0,
    parameter longint COEF  = 0
) (
    input  logic signed [WCOEF-1:0] coef,
    input  logic signed [WIN-1:0]   din,
    output logic signed [WDATA-1:0] dout
);
    localparam int WPROD = WIN + WCOEF;
    localparam longint CMAX =  (64'sd1 <<< (WCOEF-1)) - 1;
    localparam longint CMIN = -(64'sd1 <<< (WCOEF-1));
    // Saturating negate at elaboration, for the fixed case.
    localparam longint CFIX = NEG ? ((-COEF > CMAX) ? CMAX :
                                    (-COEF < CMIN) ? CMIN : -COEF) : COEF;

    logic signed [WCOEF-1:0] c;
    always_comb begin
        if (FIXED)      c = WCOEF'(CFIX);
        else if (NEG)   c = (coef == WCOEF'(CMIN)) ? WCOEF'(CMAX) : -coef;
        else            c = coef;
    end

    logic signed [WPROD-1:0] prod, rounded;
    always_comb begin
        prod    = $signed(din) * $signed(c);
        rounded = (FRAC > 0) ? ((prod + (WPROD'(1) <<< (FRAC-1))) >>> FRAC)
                             : prod;
    end

    dut_sat #(.WIN(WPROD), .WOUT(WDATA)) u_sat (.din(rounded), .dout(dout));
endmodule


// ---------------------------------------------------------------------
// One datapath-width add, saturating rather than wrapping: a filter
// that clips is bad, one that wraps is unrecognisable.  SUB subtracts,
// which is what the pre-adders of a folded antisymmetric filter do.
// ---------------------------------------------------------------------
module dut_add #(
    parameter int WDATA = 16,
    parameter bit SUB   = 1'b0
) (
    input  logic signed [WDATA-1:0] a,
    input  logic signed [WDATA-1:0] b,
    output logic signed [WDATA-1:0] sum
);
    logic signed [WDATA:0] full;
    always_comb full = SUB ? ($signed(a) - $signed(b))
                           : ($signed(a) + $signed(b));
    dut_sat #(.WIN(WDATA+1), .WOUT(WDATA)) u_sat (.din(full), .dout(sum));
endmodule


// ---------------------------------------------------------------------
// Clamp a wide signed value into a narrow one.
// ---------------------------------------------------------------------
module dut_sat #(
    parameter int WIN  = 32,
    parameter int WOUT = 16
) (
    input  logic signed [WIN-1:0]  din,
    output logic signed [WOUT-1:0] dout
);
    localparam logic signed [WIN-1:0] HI =  (WIN'(1) <<< (WOUT-1)) - 1;
    localparam logic signed [WIN-1:0] LO = -(WIN'(1) <<< (WOUT-1));
    always_comb begin
        if      ($signed(din) > HI) dout = WOUT'(HI);
        else if ($signed(din) < LO) dout = WOUT'(LO);
        else                        dout = din[WOUT-1:0];
    end
endmodule


// ---------------------------------------------------------------------
// One register.  It advances only when enabled, which makes it both the
// unit delay of the filter (enabled once per input sample) and the
// pipeline register between adder-tree levels.
// ---------------------------------------------------------------------
module dut_delay #(
    parameter int WDATA = 16
) (
    input  logic                    clk,
    input  logic                    resetn,
    input  logic                    en,
    input  logic signed [WDATA-1:0] d,
    output logic signed [WDATA-1:0] q
);
    always_ff @(posedge clk) begin
        if (!resetn) q <= '0;
        else if (en) q <= d;
    end
endmodule


// ---------------------------------------------------------------------
// dut: the filter itself.
// ---------------------------------------------------------------------
module dut #(
    // These describe the filter that was generated: the coefficients
    // below are stored in this format, so overriding them would leave
    // the two disagreeing.  They live here, rather than in the body, so
    // that the port declarations can use them.  LATENCY is here to be
    // read by whatever instantiates this, and is not used inside every
    // structure, hence the pragma.
    /* verilator lint_off UNUSEDPARAM */
    parameter int NTAPS    = 15,
    parameter int NTERM    = 15,
    parameter int NCOEF    = 15,
    parameter int WCOEF    = 10,
    parameter int FRAC     = 10,
    parameter int HEADROOM = 2,
    parameter int LATENCY  = 1,
    parameter int WDATA    = WCOEF + HEADROOM
    /* verilator lint_on UNUSEDPARAM */
) (
    input  wire                     clk,
    input  wire                     resetn,
    input  wire signed [WDATA-1:0]  din,
    input  wire                     din_strb,
    output logic signed [WDATA-1:0] dout,
    output logic                    dout_strb
);
    localparam int WTERM = WDATA + 0;
    // The impulse response, as stored integers.
    localparam longint COEF [0:NCOEF-1] = '{
        54, 94, 50, -55, -94, 62, 318, 451,
        318, 62, -94, -55, 50, 94, 54
    };

    // x[0] is this cycle's sample; x[k] is it delayed by k strobes.
    wire signed [WDATA-1:0] x    [0:NTAPS-1];
    wire signed [WTERM-1:0] term [0:NTERM-1];
    wire signed [WDATA-1:0] prod [0:NTERM-1];

    assign x[0] = din;

    generate
        for (genvar k = 1; k < NTAPS; k++) begin : g_delay
            dut_delay #(.WDATA(WDATA)) u_z (
                .clk(clk), .resetn(resetn), .en(din_strb),
                .d(x[k-1]), .q(x[k]));
        end

        for (genvar k = 0; k < NTERM; k++) begin : g_term
            assign term[k] = x[k];
        end

        for (genvar k = 0; k < NTERM; k++) begin : g_mul
            dut_mul #(
                .WDATA(WDATA), .WIN(WTERM), .WCOEF(WCOEF), .FRAC(FRAC),
                .FIXED(1'b1), .NEG(1'b0),
                .COEF(COEF[k])
            ) u_mul (
                .coef('0),
                .din(term[k]), .dout(prod[k]));
        end
    endgenerate

    // Sum the products along a chain of adders, in tap order.
    wire signed [WDATA-1:0] acc [0:NTERM-1];
    assign acc[0] = prod[0];

    generate
        for (genvar k = 1; k < NTERM; k++) begin : g_sum
            dut_add #(.WDATA(WDATA)) u_add (
                .a(acc[k-1]), .b(prod[k]), .sum(acc[k]));
        end
    endgenerate

    always_ff @(posedge clk) begin
        if (!resetn) begin
            dout      <= '0;
            dout_strb <= 1'b0;
        end else begin
            if (din_strb) dout <= acc[NTERM-1];
            dout_strb <= din_strb;
        end
    end
endmodule

/* verilator lint_on DECLFILENAME */
`default_nettype wire
