/*
 * Elliptic bandpass IIR filter, order 3
 * sample rate 1, passband edges 0.2, 0.3, stopband edges 0.12, 0.38
 * 0.5 dB passband ripple, 40 dB stopband attenuation (achieved 0.5 dB / 40 dB)
 * max |pole| = 0.918552676
 * double precision coefficients
 *
 * Cascade of 3 biquads, each transposed direct form II.
 * Generated by remez.py.
 *
 * As a library:
 *
 *     t_ctx ctx;
 *     if (init_filter(&ctx) != 0) ... out of memory ...
 *     for (...) y = process_sample(x, &ctx);
 *     free_filter(&ctx);
 *
 * As a program, which is what it builds as by default:
 *
 *     cc -O2 -o filter this.c
 *     ./filter [-o outfile] [infile]
 *
 * It reads and writes raw 64 bit float samples in native byte
 * order, stdin to stdout unless told otherwise.  Compile with
 * -DFILTER_NO_MAIN to leave main out and link it into something
 * else instead.
 */

#include <stdlib.h>

#define FILTER_SECTIONS 3

/* one row per section: b0, b1, b2, a1, a2   (a0 is 1) */
static const double filter_sos[FILTER_SECTIONS][5] = {
    {  0.23736158244665218,  0.33705736761380051,  0.23736158244665212, -2.9639834457838421e-16,  0.64723977150500911 },
    {  0.23229091419403822, -0.32985693494204316,  0.23229091419403819, -0.58750962276736118,  0.84373901851029109 },
    {  0.58631981613896944,  0, -0.58631981613896944,  0.58750962276736063,  0.84373901851029109 },
};

typedef struct {
    double *state;      /* two delay elements per section */
    size_t  sections;
} t_ctx;

/* Allocates the filter state, zeroed.  Returns 0, or -1 if out of
   memory, in which case ctx is left safe to pass to free_filter. */
int init_filter(t_ctx *ctx)
{
    ctx->sections = FILTER_SECTIONS;
    ctx->state = (double *) calloc(2 * FILTER_SECTIONS,
                                   sizeof *ctx->state);
    return ctx->state ? 0 : -1;
}

void free_filter(t_ctx *ctx)
{
    free(ctx->state);
    ctx->state = NULL;
    ctx->sections = 0;
}

/*  y     = b0*x + s0
    s0'   = b1*x - a1*y + s1
    s1'   = b2*x - a2*y            , section by section  */
double process_sample(double sample, t_ctx *ctx)
{
    size_t i;

    for (i = 0; i < ctx->sections; i++) {
        const double *c = filter_sos[i];
        double *s = ctx->state + 2 * i;
        double out = c[0] * sample + s[0];

        s[0] = c[1] * sample - c[3] * out + s[1];
        s[1] = c[2] * sample - c[4] * out;
        sample = out;
    }
    return sample;
}

#ifndef FILTER_NO_MAIN
#include <errno.h>
#include <stdio.h>
#include <string.h>

#ifdef _WIN32
#include <fcntl.h>
#include <io.h>
#else
#include <unistd.h>
#endif

/* Samples carried per read; the buffer is doubles so it stays aligned. */
#define IO_SAMPLES 4096

static const char *progname = "ellip";

static void usage(FILE *out)
{
    fprintf(out, "usage: %s [-o outfile] [infile]\n", progname);
    fprintf(out, "  Filters raw 64 bit float PCM samples (native byte order).\n");
    fprintf(out, "  infile defaults to stdin, output defaults to stdout.\n");
}

/* Filters in to out a block at a time.  Returns 0, or -1 after reporting
   an I/O error.  A trailing fragment shorter than one sample is reported
   and dropped. */
static int filter_stream(FILE *in, FILE *out, t_ctx *ctx)
{
    double buf[IO_SAMPLES];
    unsigned char *bytes = (unsigned char *) buf;
    size_t leftover = 0;
    size_t got;

    while ((got = fread(bytes + leftover, 1, sizeof buf - leftover, in)) > 0) {
        size_t total = leftover + got;
        size_t count = total / sizeof(double);
        size_t i;

        for (i = 0; i < count; i++)
            buf[i] = process_sample(buf[i], ctx);

        if (count && fwrite(buf, sizeof(double), count, out) != count) {
            fprintf(stderr, "%s: write failed: %s\n", progname, strerror(errno));
            return -1;
        }

        /* Carry any bytes that did not complete a sample into the next read. */
        leftover = total - count * sizeof(double);
        if (leftover)
            memmove(bytes, bytes + count * sizeof(double), leftover);
    }

    if (ferror(in)) {
        fprintf(stderr, "%s: read failed: %s\n", progname, strerror(errno));
        return -1;
    }
    if (leftover)
        fprintf(stderr, "%s: ignoring %lu trailing byte(s), not a whole sample\n",
                progname, (unsigned long) leftover);

    return 0;
}

int main(int argc, char **argv)
{
    const char *in_path = NULL;
    const char *out_path = NULL;
    FILE *in = stdin;
    FILE *out = stdout;
    t_ctx ctx;
    int status = 0;
    int i;

    if (argc > 0 && argv[0] && argv[0][0])
        progname = argv[0];

    for (i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-o") == 0) {
            if (++i == argc) {
                fprintf(stderr, "%s: -o needs a filename\n", progname);
                return 1;
            }
            out_path = argv[i];
        } else if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0) {
            usage(stdout);
            return 0;
        } else if (strcmp(argv[i], "-") == 0) {
            in_path = NULL;             /* explicit stdin */
        } else if (argv[i][0] == '-' && argv[i][1]) {
            fprintf(stderr, "%s: unknown option: %s\n", progname, argv[i]);
            usage(stderr);
            return 1;
        } else if (in_path == NULL) {
            in_path = argv[i];
        } else {
            fprintf(stderr, "%s: only one input file may be given\n", progname);
            return 1;
        }
    }

    if (in_path) {
        in = fopen(in_path, "rb");
        if (!in) {
            fprintf(stderr, "%s: %s: %s\n", progname, in_path, strerror(errno));
            return 1;
        }
    }

    if (out_path) {
        out = fopen(out_path, "wb");
        if (!out) {
            fprintf(stderr, "%s: %s: %s\n", progname, out_path, strerror(errno));
            if (in != stdin)
                fclose(in);
            return 1;
        }
    }

#ifdef _WIN32
    if (in == stdin)
        _setmode(_fileno(stdin), _O_BINARY);
    if (out == stdout)
        _setmode(_fileno(stdout), _O_BINARY);
#else
    /* Raw samples down a terminal are noise, and usually a forgotten -o. */
    if (out == stdout && isatty(fileno(stdout))) {
        fprintf(stderr, "%s: refusing to write binary samples to a terminal; "
                        "use -o or redirect\n", progname);
        if (in != stdin)
            fclose(in);
        return 1;
    }
#endif

    if (init_filter(&ctx) != 0) {
        fprintf(stderr, "%s: init_filter: out of memory\n", progname);
        status = 1;
    } else {
        if (filter_stream(in, out, &ctx) != 0)
            status = 1;
        free_filter(&ctx);
    }

    if (in != stdin)
        fclose(in);
    if (fflush(out) != 0 || (out != stdout && fclose(out) != 0)) {
        fprintf(stderr, "%s: %s: %s\n", progname,
                out_path ? out_path : "stdout", strerror(errno));
        status = 1;
    }

    return status;
}
#endif
