// =====================================================================
// biq: chebyshev1 lowpass IIR, order 6
//
// sample rate 1, 0.5 dB passband ripple, 40 dB stopband attenuation
// max |pole| = 0.929231
// Cascade of 3 biquads, each transposed direct form II:
//     y  = b0*x + s1
//     s1 = b1*x - a1*y + s2
//     s2 = b2*x - a2*y
// a0 is 1 for every section, so nothing multiplies by it; a1
// and a2 are given as designed and negated in the multiplier.
//
// Coefficients  16 bits, Q2.13   (value = integer * 2^-13)
// Datapath      18 bits = 16 + 2 headroom, Q4.13
//               unity is 8192, range [-16, 15.9999]
// Products are exact, then rounded to nearest and saturated; adds
// saturate.  Headroom is what keeps the adders off their limits.
//
// Costs         15 multipliers, 12 adders, 6 delays
//
// clk / resetn        synchronous, active-low reset
// din, din_strb       one sample per strobe
// dout, dout_strb     the result, 1 clock after din_strb
//
// Coefficients are elaboration-time parameters, so synthesis can
// specialise each multiplier.  There is no coefficient port.
//
// Generated by remez.py.  Lint it with, for example:
//     $ verilator --lint-only -Wall <this file>
// =====================================================================

`default_nettype none

// Everything the filter needs is in this one file, so the checker's
// one-module-per-file rule does not apply to it.
/* verilator lint_off DECLFILENAME */


// ---------------------------------------------------------------------
// One coefficient multiply.
//
// The product is formed exactly in WDATA+WCOEF bits, which leaves it
// with 2*FRAC fractional bits; half an LSB is added and it is shifted
// back down to FRAC, then saturated into the datapath width.  With
// FIXED set the coefficient is a parameter, so synthesis can fold the
// multiply down to shifts and adds; otherwise it comes from the port.
// NEG negates the coefficient, which is how the feedback taps of a
// biquad are subtracted without a separate subtractor.
// ---------------------------------------------------------------------
module biq_mul #(
    parameter int     WDATA = 16,
    parameter int     WIN   = WDATA,   // wider for a folded pre-add
    parameter int     WCOEF = 12,
    parameter int     FRAC  = 11,
    parameter bit     FIXED = 1'b1,
    parameter bit     NEG   = 1'b0,
    parameter longint COEF  = 0
) (
    input  logic signed [WCOEF-1:0] coef,
    input  logic signed [WIN-1:0]   din,
    output logic signed [WDATA-1:0] dout
);
    localparam int WPROD = WIN + WCOEF;
    localparam longint CMAX =  (64'sd1 <<< (WCOEF-1)) - 1;
    localparam longint CMIN = -(64'sd1 <<< (WCOEF-1));
    // Saturating negate at elaboration, for the fixed case.
    localparam longint CFIX = NEG ? ((-COEF > CMAX) ? CMAX :
                                    (-COEF < CMIN) ? CMIN : -COEF) : COEF;

    logic signed [WCOEF-1:0] c;
    always_comb begin
        if (FIXED)      c = WCOEF'(CFIX);
        else if (NEG)   c = (coef == WCOEF'(CMIN)) ? WCOEF'(CMAX) : -coef;
        else            c = coef;
    end

    logic signed [WPROD-1:0] prod, rounded;
    always_comb begin
        prod    = $signed(din) * $signed(c);
        rounded = (FRAC > 0) ? ((prod + (WPROD'(1) <<< (FRAC-1))) >>> FRAC)
                             : prod;
    end

    biq_sat #(.WIN(WPROD), .WOUT(WDATA)) u_sat (.din(rounded), .dout(dout));
endmodule


// ---------------------------------------------------------------------
// One datapath-width add, saturating rather than wrapping: a filter
// that clips is bad, one that wraps is unrecognisable.  SUB subtracts,
// which is what the pre-adders of a folded antisymmetric filter do.
// ---------------------------------------------------------------------
module biq_add #(
    parameter int WDATA = 16,
    parameter bit SUB   = 1'b0
) (
    input  logic signed [WDATA-1:0] a,
    input  logic signed [WDATA-1:0] b,
    output logic signed [WDATA-1:0] sum
);
    logic signed [WDATA:0] full;
    always_comb full = SUB ? ($signed(a) - $signed(b))
                           : ($signed(a) + $signed(b));
    biq_sat #(.WIN(WDATA+1), .WOUT(WDATA)) u_sat (.din(full), .dout(sum));
endmodule


// ---------------------------------------------------------------------
// Clamp a wide signed value into a narrow one.
// ---------------------------------------------------------------------
module biq_sat #(
    parameter int WIN  = 32,
    parameter int WOUT = 16
) (
    input  logic signed [WIN-1:0]  din,
    output logic signed [WOUT-1:0] dout
);
    localparam logic signed [WIN-1:0] HI =  (WIN'(1) <<< (WOUT-1)) - 1;
    localparam logic signed [WIN-1:0] LO = -(WIN'(1) <<< (WOUT-1));
    always_comb begin
        if      ($signed(din) > HI) dout = WOUT'(HI);
        else if ($signed(din) < LO) dout = WOUT'(LO);
        else                        dout = din[WOUT-1:0];
    end
endmodule


// ---------------------------------------------------------------------
// One register.  It advances only when enabled, which makes it both the
// unit delay of the filter (enabled once per input sample) and the
// pipeline register between adder-tree levels.
// ---------------------------------------------------------------------
module biq_delay #(
    parameter int WDATA = 16
) (
    input  logic                    clk,
    input  logic                    resetn,
    input  logic                    en,
    input  logic signed [WDATA-1:0] d,
    output logic signed [WDATA-1:0] q
);
    always_ff @(posedge clk) begin
        if (!resetn) q <= '0;
        else if (en) q <= d;
    end
endmodule


// ---------------------------------------------------------------------
// biq: the filter itself.
// ---------------------------------------------------------------------
module biq #(
    // These describe the filter that was generated: the coefficients
    // below are stored in this format, so overriding them would leave
    // the two disagreeing.  They live here, rather than in the body, so
    // that the port declarations can use them.  LATENCY is here to be
    // read by whatever instantiates this, and is not used inside every
    // structure, hence the pragma.
    /* verilator lint_off UNUSEDPARAM */
    parameter int NSEC     = 3,
    parameter int NCOEF    = 15,
    parameter int WCOEF    = 16,
    parameter int FRAC     = 13,
    parameter int HEADROOM = 2,
    parameter int LATENCY  = 1,
    parameter int WDATA    = WCOEF + HEADROOM
    /* verilator lint_on UNUSEDPARAM */
) (
    input  wire                     clk,
    input  wire                     resetn,
    input  wire signed [WDATA-1:0]  din,
    input  wire                     din_strb,
    output logic signed [WDATA-1:0] dout,
    output logic                    dout_strb
);
    // Five stored integers per section, in the order b0 b1 b2 a1 a2.
    localparam longint COEF [0:NCOEF-1] = '{
        27, 54, 27, -9991, 3605,
        8192, 16384, 8192, -6965, 5074,
        8192, 16384, 8192, -4560, 7074
    };

    // chain[0] is the input; chain[s+1] is the output of section s.
    wire signed [WDATA-1:0] chain [0:NSEC];
    assign chain[0] = din;

    generate
        for (genvar s = 0; s < NSEC; s++) begin : g_sec
            wire signed [WDATA-1:0] x = chain[s];
            wire signed [WDATA-1:0] y;
            wire signed [WDATA-1:0] s1, s2;          // delay outputs
            wire signed [WDATA-1:0] pb0, pb1, pb2, pa1, pa2;
            wire signed [WDATA-1:0] u1, s1_next, s2_next;

            // The five multipliers.  a1 and a2 get NEG, which turns
            // their adds into the subtractions the recursion wants.
            biq_mul #(
                .WDATA(WDATA), .WCOEF(WCOEF), .FRAC(FRAC),
                .FIXED(1'b1), .NEG(1'b0),
                .COEF(COEF[s*5 + 0])
            ) u_mul_pb0 (
                .coef('0),
                .din(x), .dout(pb0));

            biq_mul #(
                .WDATA(WDATA), .WCOEF(WCOEF), .FRAC(FRAC),
                .FIXED(1'b1), .NEG(1'b0),
                .COEF(COEF[s*5 + 1])
            ) u_mul_pb1 (
                .coef('0),
                .din(x), .dout(pb1));

            biq_mul #(
                .WDATA(WDATA), .WCOEF(WCOEF), .FRAC(FRAC),
                .FIXED(1'b1), .NEG(1'b0),
                .COEF(COEF[s*5 + 2])
            ) u_mul_pb2 (
                .coef('0),
                .din(x), .dout(pb2));

            biq_mul #(
                .WDATA(WDATA), .WCOEF(WCOEF), .FRAC(FRAC),
                .FIXED(1'b1), .NEG(1'b1),
                .COEF(COEF[s*5 + 3])
            ) u_mul_pa1 (
                .coef('0),
                .din(y), .dout(pa1));

            biq_mul #(
                .WDATA(WDATA), .WCOEF(WCOEF), .FRAC(FRAC),
                .FIXED(1'b1), .NEG(1'b1),
                .COEF(COEF[s*5 + 4])
            ) u_mul_pa2 (
                .coef('0),
                .din(y), .dout(pa2));

            // y = b0*x + s1
            biq_add #(.WDATA(WDATA)) u_add_y (
                .a(pb0), .b(s1), .sum(y));

            // s1 <- b1*x - a1*y + s2
            biq_add #(.WDATA(WDATA)) u_add_u1 (
                .a(pb1), .b(pa1), .sum(u1));
            biq_add #(.WDATA(WDATA)) u_add_s1 (
                .a(u1), .b(s2), .sum(s1_next));

            // s2 <- b2*x - a2*y
            biq_add #(.WDATA(WDATA)) u_add_s2 (
                .a(pb2), .b(pa2), .sum(s2_next));

            biq_delay #(.WDATA(WDATA)) u_z1 (
                .clk(clk), .resetn(resetn), .en(din_strb),
                .d(s1_next), .q(s1));
            biq_delay #(.WDATA(WDATA)) u_z2 (
                .clk(clk), .resetn(resetn), .en(din_strb),
                .d(s2_next), .q(s2));

            assign chain[s+1] = y;
        end
    endgenerate

    always_ff @(posedge clk) begin
        if (!resetn) begin
            dout      <= '0;
            dout_strb <= 1'b0;
        end else begin
            if (din_strb) dout <= chain[NSEC];
            dout_strb <= din_strb;
        end
    end
endmodule

/* verilator lint_on DECLFILENAME */
`default_nettype wire
