-- =====================================================================
-- biq: chebyshev1 lowpass IIR, order 6
--
-- sample rate 1, 0.5 dB passband ripple, 40 dB stopband attenuation
-- max |pole| = 0.929231
-- Cascade of 3 biquads, each transposed direct form II:
--     y  = b0*x + s1
--     s1 = b1*x - a1*y + s2
--     s2 = b2*x - a2*y
-- a0 is 1 for every section, so nothing multiplies by it; a1
-- and a2 are given as designed and negated in the multiplier.
--
-- Coefficients  16 bits, Q1.14   (value = integer * 2^-14)
-- Datapath      18 bits = 16 + 2 headroom, Q3.14
--               unity is 16384, range [-8, 7.99994]
-- Products are exact, then rounded to nearest and saturated; adds
-- saturate.  Headroom is what keeps the adders off their limits.
--
-- Costs         15 multipliers, 12 adders, 6 delays
--
-- clk / resetn        synchronous, active-low reset
-- din, din_strb       one sample per strobe
-- dout, dout_strb     the result, 1 clock after din_strb
--
-- Coefficients are elaboration-time generics, so synthesis can
-- specialise each multiplier.  There is no coefficient port.
--
-- Generated by remez.py.  Analyse it with, for example:
--     $ ghdl -a --std=93 <this file>
-- =====================================================================


-- ---------------------------------------------------------------------
-- Clamp a wide signed value into a narrow one.  Overflow is detected by
-- looking at the bits above the target's sign bit: if they all match it,
-- the value fits.  That avoids computing the limits as integers, which
-- would themselves overflow for a wide datapath.
-- ---------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity biq_sat is
    generic (
        WIN  : positive := 32;
        WOUT : positive := 16);
    port (
        din  : in  signed(WIN-1 downto 0);
        dout : out signed(WOUT-1 downto 0));
end entity biq_sat;

architecture rtl of biq_sat is
    -- 0111..1 and 1000..0.  Built by shifting rather than as an
    -- aggregate, because a choice that depends on a generic is not
    -- locally static and so cannot be mixed with 'others'.
    constant HI : signed(WOUT-1 downto 0) := to_signed(-1, WOUT) srl 1;
    constant LO : signed(WOUT-1 downto 0) := not HI;
begin
    process (din)
        variable top : signed(WIN-WOUT downto 0);
    begin
        top := din(WIN-1 downto WOUT-1);
        if top = to_signed(0, top'length) or
           top = to_signed(-1, top'length) then
            dout <= din(WOUT-1 downto 0);
        elsif din(WIN-1) = '0' then
            dout <= HI;
        else
            dout <= LO;
        end if;
    end process;
end architecture rtl;


-- ---------------------------------------------------------------------
-- One coefficient multiply.
--
-- The product is formed exactly in WDATA+WCOEF bits, which leaves it with
-- 2*FRAC fractional bits; half an LSB is added and it is shifted back
-- down to FRAC, then saturated into the datapath width.  With FIXED true
-- the coefficient is a generic, so synthesis can fold the multiply down
-- to shifts and adds; otherwise it comes from the port.  NEG negates it,
-- which is how the feedback taps of a biquad are subtracted without a
-- separate subtractor.
-- ---------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity biq_mul is
    generic (
        WDATA : positive := 16;
        WIN   : positive := 16;   -- wider for a folded pre-add
        WCOEF : positive := 12;
        FRAC  : natural  := 11;
        FIXED : boolean  := true;
        NEG   : boolean  := false;
        COEF_FIXED : integer := 0);   -- COEF would clash with the port
    port (
        coef : in  signed(WCOEF-1 downto 0);
        din  : in  signed(WIN-1 downto 0);
        dout : out signed(WDATA-1 downto 0));
end entity biq_mul;

architecture rtl of biq_mul is
    constant WPROD : positive := WIN + WCOEF;
    constant CMAX  : integer  := 2**(WCOEF-1) - 1;
    constant CMIN  : integer  := -(2**(WCOEF-1));
    -- Saturating negate at elaboration, for the fixed case.  A
    -- conditional expression in a constant would need VHDL-2019, so this
    -- is a function.
    function chosen (v : integer; flip : boolean) return integer is
    begin
        if not flip then
            return v;
        elsif -v > CMAX then
            return CMAX;
        elsif -v < CMIN then
            return CMIN;
        else
            return -v;
        end if;
    end function chosen;
    constant CFIX : integer := chosen(COEF_FIXED, NEG);

    signal c       : signed(WCOEF-1 downto 0);
    signal rounded : signed(WPROD-1 downto 0);
begin
    coefficient : process (coef)
    begin
        if FIXED then
            c <= to_signed(CFIX, WCOEF);
        elsif NEG then
            if coef = to_signed(CMIN, WCOEF) then
                c <= to_signed(CMAX, WCOEF);
            else
                c <= -coef;
            end if;
        else
            c <= coef;
        end if;
    end process coefficient;

    product : process (din, c)
        variable prod : signed(WPROD-1 downto 0);
        variable half : signed(WPROD-1 downto 0);
    begin
        prod := din * c;
        if FRAC > 0 then
            half    := to_signed(0, WPROD);
            half(FRAC-1) := '1';
            rounded <= shift_right(prod + half, FRAC);
        else
            rounded <= prod;
        end if;
    end process product;

    u_sat : entity work.biq_sat
        generic map (WIN => WPROD, WOUT => WDATA)
        port map (din => rounded, dout => dout);
end architecture rtl;


-- ---------------------------------------------------------------------
-- One datapath-width add, saturating rather than wrapping: a filter that
-- clips is bad, one that wraps is unrecognisable.  SUB subtracts, which
-- is what the pre-adders of a folded antisymmetric filter do.
-- ---------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity biq_add is
    generic (
        WDATA : positive := 16;
        SUB   : boolean  := false);
    port (
        a   : in  signed(WDATA-1 downto 0);
        b   : in  signed(WDATA-1 downto 0);
        sum : out signed(WDATA-1 downto 0));
end entity biq_add;

architecture rtl of biq_add is
    signal full : signed(WDATA downto 0);
begin
    process (a, b)
    begin
        if SUB then
            full <= resize(a, WDATA+1) - resize(b, WDATA+1);
        else
            full <= resize(a, WDATA+1) + resize(b, WDATA+1);
        end if;
    end process;

    u_sat : entity work.biq_sat
        generic map (WIN => WDATA+1, WOUT => WDATA)
        port map (din => full, dout => sum);
end architecture rtl;


-- ---------------------------------------------------------------------
-- One register.  It advances only when enabled, which makes it both the
-- unit delay of the filter (enabled once per input sample) and the
-- pipeline register between adder-tree levels.
-- ---------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity biq_delay is
    generic (
        WDATA : positive := 16);
    port (
        clk    : in  std_logic;
        resetn : in  std_logic;
        en     : in  std_logic;
        d      : in  signed(WDATA-1 downto 0);
        q      : out signed(WDATA-1 downto 0));
end entity biq_delay;

architecture rtl of biq_delay is
begin
    process (clk)
    begin
        if rising_edge(clk) then
            if resetn = '0' then
                q <= (others => '0');
            elsif en = '1' then
                q <= d;
            end if;
        end if;
    end process;
end architecture rtl;


-- ---------------------------------------------------------------------
-- biq: the filter itself.
-- ---------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity biq is
    generic (
        -- These describe the filter that was generated: the
        -- coefficients below are stored in this format, so overriding
        -- them would leave the two disagreeing.  LATENCY is here to be
        -- read by whatever instantiates this.
        NSEC     : positive := 3;
        NCOEF    : positive := 15;
        WCOEF    : positive := 16;
        FRAC     : natural  := 14;
        HEADROOM : natural  := 2;
        LATENCY  : positive := 1;
        WDATA    : positive := 18);
    port (
        clk       : in  std_logic;
        resetn    : in  std_logic;
        din       : in  signed(WDATA-1 downto 0);
        din_strb  : in  std_logic;
        dout      : out signed(WDATA-1 downto 0);
        dout_strb : out std_logic);
end entity biq;

architecture rtl of biq is
    constant WTERM : positive := WDATA + 0;

    type data_array_t is array (natural range <>) of signed(WDATA-1 downto 0);
    type term_array_t is array (natural range <>) of signed(WTERM-1 downto 0);
    type coef_array_t is array (natural range <>) of integer;

    -- Five stored integers per section, in the order b0 b1 b2 a1 a2.
    constant COEF : coef_array_t(0 to NCOEF-1) := (
        903, 1806, 903, -19982, 7209,
        3109, 6219, 3109, -13930, 10148,
        5120, 10241, 5120, -9119, 14147
    );

    signal chain : data_array_t(0 to NSEC);
begin
    -- chain(0) is the input; chain(s+1) is the output of section s.
    chain(0) <= din;

    g_sec : for s in 0 to NSEC-1 generate
        signal x  : signed(WDATA-1 downto 0);
        signal y  : signed(WDATA-1 downto 0);
        signal s1, s2 : signed(WDATA-1 downto 0);      -- delay outputs
        signal pb0, pb1, pb2, pa1, pa2 : signed(WDATA-1 downto 0);
        signal u1, s1_next, s2_next    : signed(WDATA-1 downto 0);
    begin
        x <= chain(s);

        -- The five multipliers.  a1 and a2 get NEG, which turns their
        -- adds into the subtractions the recursion wants.
        u_mul_pb0 : entity work.biq_mul
            generic map (WDATA => WDATA, WIN => WDATA, WCOEF => WCOEF, FRAC => FRAC,
                         FIXED => true, NEG => false,
                         COEF_FIXED => COEF(s*5 + 0))
            port map (coef => to_signed(0, WCOEF),
                      din => x, dout => pb0);

        u_mul_pb1 : entity work.biq_mul
            generic map (WDATA => WDATA, WIN => WDATA, WCOEF => WCOEF, FRAC => FRAC,
                         FIXED => true, NEG => false,
                         COEF_FIXED => COEF(s*5 + 1))
            port map (coef => to_signed(0, WCOEF),
                      din => x, dout => pb1);

        u_mul_pb2 : entity work.biq_mul
            generic map (WDATA => WDATA, WIN => WDATA, WCOEF => WCOEF, FRAC => FRAC,
                         FIXED => true, NEG => false,
                         COEF_FIXED => COEF(s*5 + 2))
            port map (coef => to_signed(0, WCOEF),
                      din => x, dout => pb2);

        u_mul_pa1 : entity work.biq_mul
            generic map (WDATA => WDATA, WIN => WDATA, WCOEF => WCOEF, FRAC => FRAC,
                         FIXED => true, NEG => true,
                         COEF_FIXED => COEF(s*5 + 3))
            port map (coef => to_signed(0, WCOEF),
                      din => y, dout => pa1);

        u_mul_pa2 : entity work.biq_mul
            generic map (WDATA => WDATA, WIN => WDATA, WCOEF => WCOEF, FRAC => FRAC,
                         FIXED => true, NEG => true,
                         COEF_FIXED => COEF(s*5 + 4))
            port map (coef => to_signed(0, WCOEF),
                      din => y, dout => pa2);

        -- y = b0*x + s1
        u_add_y : entity work.biq_add
            generic map (WDATA => WDATA)
            port map (a => pb0, b => s1, sum => y);

        -- s1 <- b1*x - a1*y + s2
        u_add_u1 : entity work.biq_add
            generic map (WDATA => WDATA)
            port map (a => pb1, b => pa1, sum => u1);
        u_add_s1 : entity work.biq_add
            generic map (WDATA => WDATA)
            port map (a => u1, b => s2, sum => s1_next);

        -- s2 <- b2*x - a2*y
        u_add_s2 : entity work.biq_add
            generic map (WDATA => WDATA)
            port map (a => pb2, b => pa2, sum => s2_next);

        u_z1 : entity work.biq_delay
            generic map (WDATA => WDATA)
            port map (clk => clk, resetn => resetn, en => din_strb,
                      d => s1_next, q => s1);
        u_z2 : entity work.biq_delay
            generic map (WDATA => WDATA)
            port map (clk => clk, resetn => resetn, en => din_strb,
                      d => s2_next, q => s2);

        chain(s+1) <= y;
    end generate g_sec;

    output : process (clk)
    begin
        if rising_edge(clk) then
            if resetn = '0' then
                dout      <= (others => '0');
                dout_strb <= '0';
            else
                if din_strb = '1' then
                    dout <= chain(NSEC);
                end if;
                dout_strb <= din_strb;
            end if;
        end if;
    end process output;
end architecture rtl;
