-- =====================================================================
-- dut: Parks-McClellan FIR, type 1 (symmetric), N = 15
--
-- sample rate 1, bands 0-0.2, 0.25-0.5
-- weighted delta = 0.27933 as designed
-- Structure: one multiplier reused over the taps, one term per clock.
-- Folded: the response is linear phase, so the taps are equal in
-- pairs and one pre-add plus one multiply serves two of them,
-- which is 15 multipliers down to 8.  Note that a folded
-- filter rounds once per pair rather than once per tap, so it is not
-- bit-identical to the unfolded one -- it is very slightly better.
--
-- Coefficients  10 bits, Q-1.10   (value = integer * 2^-10)
-- Datapath      12 bits = 10 + 2 headroom, Q1.10
--               unity is 1024, range [-2, 1.99902]
-- Products are exact, then rounded to nearest and saturated; adds
-- saturate.  Headroom is what keeps the adders off their limits.
--
-- Costs         1 multiplier, 2 adders, 15 delays
--
-- clk / resetn        synchronous, active-low reset
-- din, din_strb       one sample per strobe
-- dout, dout_strb     the result, 10 clocks after din_strb
--                     strobes must be at least LATENCY clocks
--                     apart; any arriving while busy are ignored
--
-- Coefficients arrive on the packed 'coeff' port and may change
-- while the filter runs.  Slice k is
-- coeff((k+1)*WCOEF-1 downto k*WCOEF):
--
--   [  0] h[0]   for x[0] + x[14]
--   [  1] h[1]   for x[1] + x[13]
--   [  2] h[2]   for x[2] + x[12]
--   [  3] h[3]   for x[3] + x[11]
--   [  4] h[4]   for x[4] + x[10]
--   [  5] h[5]   for x[5] + x[9]
--   [  6] h[6]   for x[6] + x[8]
--   [  7] h[7] (centre tap)
--
-- Generated by remez.py.  Analyse it with, for example:
--     $ ghdl -a --std=93 <this file>
-- =====================================================================


-- ---------------------------------------------------------------------
-- Clamp a wide signed value into a narrow one.  Overflow is detected by
-- looking at the bits above the target's sign bit: if they all match it,
-- the value fits.  That avoids computing the limits as integers, which
-- would themselves overflow for a wide datapath.
-- ---------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity dut_sat is
    generic (
        WIN  : positive := 32;
        WOUT : positive := 16);
    port (
        din  : in  signed(WIN-1 downto 0);
        dout : out signed(WOUT-1 downto 0));
end entity dut_sat;

architecture rtl of dut_sat is
    -- 0111..1 and 1000..0.  Built by shifting rather than as an
    -- aggregate, because a choice that depends on a generic is not
    -- locally static and so cannot be mixed with 'others'.
    constant HI : signed(WOUT-1 downto 0) := to_signed(-1, WOUT) srl 1;
    constant LO : signed(WOUT-1 downto 0) := not HI;
begin
    process (din)
        variable top : signed(WIN-WOUT downto 0);
    begin
        top := din(WIN-1 downto WOUT-1);
        if top = to_signed(0, top'length) or
           top = to_signed(-1, top'length) then
            dout <= din(WOUT-1 downto 0);
        elsif din(WIN-1) = '0' then
            dout <= HI;
        else
            dout <= LO;
        end if;
    end process;
end architecture rtl;


-- ---------------------------------------------------------------------
-- One coefficient multiply.
--
-- The product is formed exactly in WDATA+WCOEF bits, which leaves it with
-- 2*FRAC fractional bits; half an LSB is added and it is shifted back
-- down to FRAC, then saturated into the datapath width.  With FIXED true
-- the coefficient is a generic, so synthesis can fold the multiply down
-- to shifts and adds; otherwise it comes from the port.  NEG negates it,
-- which is how the feedback taps of a biquad are subtracted without a
-- separate subtractor.
-- ---------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity dut_mul is
    generic (
        WDATA : positive := 16;
        WIN   : positive := 16;   -- wider for a folded pre-add
        WCOEF : positive := 12;
        FRAC  : natural  := 11;
        FIXED : boolean  := true;
        NEG   : boolean  := false;
        COEF_FIXED : integer := 0);   -- COEF would clash with the port
    port (
        coef : in  signed(WCOEF-1 downto 0);
        din  : in  signed(WIN-1 downto 0);
        dout : out signed(WDATA-1 downto 0));
end entity dut_mul;

architecture rtl of dut_mul is
    constant WPROD : positive := WIN + WCOEF;
    constant CMAX  : integer  := 2**(WCOEF-1) - 1;
    constant CMIN  : integer  := -(2**(WCOEF-1));
    -- Saturating negate at elaboration, for the fixed case.  A
    -- conditional expression in a constant would need VHDL-2019, so this
    -- is a function.
    function chosen (v : integer; flip : boolean) return integer is
    begin
        if not flip then
            return v;
        elsif -v > CMAX then
            return CMAX;
        elsif -v < CMIN then
            return CMIN;
        else
            return -v;
        end if;
    end function chosen;
    constant CFIX : integer := chosen(COEF_FIXED, NEG);

    signal c       : signed(WCOEF-1 downto 0);
    signal rounded : signed(WPROD-1 downto 0);
begin
    coefficient : process (coef)
    begin
        if FIXED then
            c <= to_signed(CFIX, WCOEF);
        elsif NEG then
            if coef = to_signed(CMIN, WCOEF) then
                c <= to_signed(CMAX, WCOEF);
            else
                c <= -coef;
            end if;
        else
            c <= coef;
        end if;
    end process coefficient;

    product : process (din, c)
        variable prod : signed(WPROD-1 downto 0);
        variable half : signed(WPROD-1 downto 0);
    begin
        prod := din * c;
        if FRAC > 0 then
            half    := to_signed(0, WPROD);
            half(FRAC-1) := '1';
            rounded <= shift_right(prod + half, FRAC);
        else
            rounded <= prod;
        end if;
    end process product;

    u_sat : entity work.dut_sat
        generic map (WIN => WPROD, WOUT => WDATA)
        port map (din => rounded, dout => dout);
end architecture rtl;


-- ---------------------------------------------------------------------
-- One datapath-width add, saturating rather than wrapping: a filter that
-- clips is bad, one that wraps is unrecognisable.  SUB subtracts, which
-- is what the pre-adders of a folded antisymmetric filter do.
-- ---------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity dut_add is
    generic (
        WDATA : positive := 16;
        SUB   : boolean  := false);
    port (
        a   : in  signed(WDATA-1 downto 0);
        b   : in  signed(WDATA-1 downto 0);
        sum : out signed(WDATA-1 downto 0));
end entity dut_add;

architecture rtl of dut_add is
    signal full : signed(WDATA downto 0);
begin
    process (a, b)
    begin
        if SUB then
            full <= resize(a, WDATA+1) - resize(b, WDATA+1);
        else
            full <= resize(a, WDATA+1) + resize(b, WDATA+1);
        end if;
    end process;

    u_sat : entity work.dut_sat
        generic map (WIN => WDATA+1, WOUT => WDATA)
        port map (din => full, dout => sum);
end architecture rtl;


-- ---------------------------------------------------------------------
-- A widening add for the pre-adders of a folded filter.  It sums two
-- samples that may each be at full scale, so the result is one bit wider
-- and nothing is clipped: saturating here would throw away signal rather
-- than round it.  SUB subtracts, as an antisymmetric filter needs.
-- ---------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity dut_addw is
    generic (
        WDATA : positive := 16;
        SUB   : boolean  := false);
    port (
        a   : in  signed(WDATA-1 downto 0);
        b   : in  signed(WDATA-1 downto 0);
        sum : out signed(WDATA downto 0));
end entity dut_addw;

architecture rtl of dut_addw is
begin
    process (a, b)
    begin
        if SUB then
            sum <= resize(a, WDATA+1) - resize(b, WDATA+1);
        else
            sum <= resize(a, WDATA+1) + resize(b, WDATA+1);
        end if;
    end process;
end architecture rtl;


-- ---------------------------------------------------------------------
-- One register.  It advances only when enabled, which makes it both the
-- unit delay of the filter (enabled once per input sample) and the
-- pipeline register between adder-tree levels.
-- ---------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity dut_delay is
    generic (
        WDATA : positive := 16);
    port (
        clk    : in  std_logic;
        resetn : in  std_logic;
        en     : in  std_logic;
        d      : in  signed(WDATA-1 downto 0);
        q      : out signed(WDATA-1 downto 0));
end entity dut_delay;

architecture rtl of dut_delay is
begin
    process (clk)
    begin
        if rising_edge(clk) then
            if resetn = '0' then
                q <= (others => '0');
            elsif en = '1' then
                q <= d;
            end if;
        end if;
    end process;
end architecture rtl;


-- ---------------------------------------------------------------------
-- dut: the filter itself.
-- ---------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity dut is
    generic (
        -- These describe the filter that was generated: the
        -- coefficients below are stored in this format, so overriding
        -- them would leave the two disagreeing.  LATENCY is here to be
        -- read by whatever instantiates this.
        NTAPS    : positive := 15;
        NTERM    : positive := 8;
        NCOEF    : positive := 8;
        WCOEF    : positive := 10;
        FRAC     : natural  := 10;
        HEADROOM : natural  := 2;
        LATENCY  : positive := 10;
        WDATA    : positive := 12);
    port (
        clk       : in  std_logic;
        resetn    : in  std_logic;
        din       : in  signed(WDATA-1 downto 0);
        din_strb  : in  std_logic;
        coeff     : in  signed(NCOEF*WCOEF-1 downto 0);
        dout      : out signed(WDATA-1 downto 0);
        dout_strb : out std_logic);
end entity dut;

architecture rtl of dut is
    constant WTERM : positive := WDATA + 1;

    type data_array_t is array (natural range <>) of signed(WDATA-1 downto 0);
    type term_array_t is array (natural range <>) of signed(WTERM-1 downto 0);
    type coef_array_t is array (natural range <>) of integer;

    -- One per multiply: the coefficient a folded pair shares.
    constant COEF : coef_array_t(0 to NCOEF-1) := (
        54, 94, 50, -55, -94, 62, 318, 451
    );

    signal mem      : data_array_t(0 to NTAPS-1);
    signal wp, rp   : integer range 0 to NTAPS-1;
    signal rp2      : integer range 0 to NTAPS-1;
    signal k        : integer range 0 to NTERM-1;
    signal busy     : std_logic;
    signal acc      : signed(WDATA-1 downto 0);
    signal acc_next : signed(WDATA-1 downto 0);
    signal sample   : signed(WDATA-1 downto 0);
    signal term_in  : signed(WTERM-1 downto 0);
    signal prod     : signed(WDATA-1 downto 0);
    signal coef_sel : signed(WCOEF-1 downto 0);
    signal mirror   : signed(WDATA-1 downto 0);
    signal paired   : signed(WTERM-1 downto 0);
begin
    -- One multiplier, reused.  The delay line is a register file with a
    -- write pointer rather than a shift chain, so any tap can be fetched
    -- by index; the accumulator then walks the terms one per clock.
    sample <= mem(rp);
    mirror <= mem(rp2);

    u_pre : entity work.dut_addw
        generic map (WDATA => WDATA, SUB => false)
        port map (a => sample, b => mirror, sum => paired);

    -- The centre tap of an odd-length symmetric filter has no
    -- partner, so on that term the pre-adder is bypassed.
    term_in <= resize(sample, WTERM) when k = NTERM-1 else paired;

    -- One multiplier serves every tap, so the coefficient is looked up
    -- per term rather than built into a multiplier.
    coef_sel <= coeff((k+1)*WCOEF-1 downto k*WCOEF);

    u_mul : entity work.dut_mul
        generic map (WDATA => WDATA, WIN => WTERM, WCOEF => WCOEF,
                     FRAC => FRAC, FIXED => false, NEG => false)
        port map (coef => coef_sel, din => term_in, dout => prod);

    u_acc : entity work.dut_add
        generic map (WDATA => WDATA)
        port map (a => acc, b => prod, sum => acc_next);

    sequencer : process (clk)
    begin
        if rising_edge(clk) then
            if resetn = '0' then
                -- The delay line is cleared, as the shift-register
                -- structures clear theirs: without it the first NTAPS
                -- outputs would depend on whatever the memory held.
                for i in 0 to NTAPS-1 loop
                    mem(i) <= (others => '0');
                end loop;
                wp        <= 0;
                rp        <= 0;
                rp2       <= 0;
                k         <= 0;
                busy      <= '0';
                acc       <= (others => '0');
                dout      <= (others => '0');
                dout_strb <= '0';
            else
                dout_strb <= '0';

                -- A strobe arriving mid-sum would corrupt it, so it is
                -- ignored: keep them LATENCY clocks apart.
                if din_strb = '1' and busy = '0' then
                    mem(wp) <= din;
                    rp      <= wp;
                    if wp = NTAPS-1 then
                        rp2 <= 0;
                    else
                        rp2 <= wp + 1;
                    end if;
                    if wp = NTAPS-1 then
                        wp <= 0;
                    else
                        wp <= wp + 1;
                    end if;
                    k       <= 0;
                    acc     <= (others => '0');
                    busy    <= '1';
                elsif busy = '1' then
                    acc <= acc_next;
                    if k = NTERM-1 then
                        busy      <= '0';
                        dout      <= acc_next;
                        dout_strb <= '1';
                    else
                        k <= k + 1;
                        if rp = 0 then
                            rp <= NTAPS-1;
                        else
                            rp <= rp - 1;
                        end if;
                        if rp2 = NTAPS-1 then
                            rp2 <= 0;
                        else
                            rp2 <= rp2 + 1;
                        end if;
                    end if;
                end if;
            end if;
        end if;
    end process sequencer;
end architecture rtl;
