/// Self-contained C for the filter that was designed.
///
/// The generated file is both a library and a program. As a library it is
/// `init_filter` / `process_sample` / `free_filter`; as a program it filters
/// raw 64-bit floats from stdin to stdout, which is what makes it composable
/// in a pipeline. `-DFILTER_NO_MAIN` leaves the program out.
///
/// It runs in double precision but with the coefficients that were actually
/// chosen -- rounded ones included -- so it is the filter you would build, not
/// the one you asked for.
library;

import 'fir_core.dart' as fir;
import 'fixed_point.dart' as fx;
import 'format.dart';
import 'labels.dart';
import 'iir_core.dart' as iir;

/// One line describing the word length, for an export header.
String formatNote(fx.Fixed? fixed) => fixed == null
    ? 'double precision coefficients'
    : '${fixed.bits}-bit fixed point, ${fixed.qFormat}: '
        'value = integer * 2^-${fixed.fracBits}';

String _preamble(String title, List<String> detail, String structure) => [
      '/*',
      ' * $title',
      for (final line in detail) ' * $line',
      ' *',
      ' * $structure',
      // The Python writes its own name here. This is a different program, and
      // saying so is worth more than a byte-identical header; the comparison
      // test normalises this one line.
      ' * Generated by $programName.',
      ' *',
      ' * As a library:',
      ' *',
      ' *     t_ctx ctx;',
      ' *     if (init_filter(&ctx) != 0) ... out of memory ...',
      ' *     for (...) y = process_sample(x, &ctx);',
      ' *     free_filter(&ctx);',
      ' *',
      ' * As a program, which is what it builds as by default:',
      ' *',
      ' *     cc -O2 -o filter this.c',
      ' *     ./filter [-o outfile] [infile]',
      ' *',
      ' * It reads and writes raw 64 bit float samples in native byte',
      ' * order, stdin to stdout unless told otherwise.  Compile with',
      ' * -DFILTER_NO_MAIN to leave main out and link it into something',
      ' * else instead.',
      ' */',
      '',
      '#include <stdlib.h>',
      '',
      '',
    ].join('\n');

/// The stand-alone program wrapped round the filter.
///
/// Raw 64 bit floats in native byte order, in and out: a filter is usually one
/// stage of a pipeline, and text costs a conversion each way and every bit
/// below the seventeenth digit. Reads stdin and writes stdout unless given
/// filenames, so it composes.
String _main(String name) => [
      '',
      '#ifndef FILTER_NO_MAIN',
      '#include <errno.h>',
      '#include <stdio.h>',
      '#include <string.h>',
      '',
      '#ifdef _WIN32',
      '#include <fcntl.h>',
      '#include <io.h>',
      '#else',
      '#include <unistd.h>',
      '#endif',
      '',
      '/* Samples carried per read; the buffer is doubles so it stays aligned. */',
      '#define IO_SAMPLES 4096',
      '',
      'static const char *progname = "$name";',
      '',
      'static void usage(FILE *out)',
      '{',
      r'    fprintf(out, "usage: %s [-o outfile] [infile]\n", progname);',
      r'    fprintf(out, "  Filters raw 64 bit float PCM samples (native byte order).\n");',
      r'    fprintf(out, "  infile defaults to stdin, output defaults to stdout.\n");',
      '}',
      '',
      '/* Filters in to out a block at a time.  Returns 0, or -1 after reporting',
      '   an I/O error.  A trailing fragment shorter than one sample is reported',
      '   and dropped. */',
      'static int filter_stream(FILE *in, FILE *out, t_ctx *ctx)',
      '{',
      '    double buf[IO_SAMPLES];',
      '    unsigned char *bytes = (unsigned char *) buf;',
      '    size_t leftover = 0;',
      '    size_t got;',
      '',
      '    while ((got = fread(bytes + leftover, 1, sizeof buf - leftover, in)) > 0) {',
      '        size_t total = leftover + got;',
      '        size_t count = total / sizeof(double);',
      '        size_t i;',
      '',
      '        for (i = 0; i < count; i++)',
      '            buf[i] = process_sample(buf[i], ctx);',
      '',
      '        if (count && fwrite(buf, sizeof(double), count, out) != count) {',
      r'            fprintf(stderr, "%s: write failed: %s\n", progname, strerror(errno));',
      '            return -1;',
      '        }',
      '',
      '        /* Carry any bytes that did not complete a sample into the next read. */',
      '        leftover = total - count * sizeof(double);',
      '        if (leftover)',
      '            memmove(bytes, bytes + count * sizeof(double), leftover);',
      '    }',
      '',
      '    if (ferror(in)) {',
      r'        fprintf(stderr, "%s: read failed: %s\n", progname, strerror(errno));',
      '        return -1;',
      '    }',
      '    if (leftover)',
      r'        fprintf(stderr, "%s: ignoring %lu trailing byte(s), not a whole sample\n",',
      '                progname, (unsigned long) leftover);',
      '',
      '    return 0;',
      '}',
      '',
      'int main(int argc, char **argv)',
      '{',
      '    const char *in_path = NULL;',
      '    const char *out_path = NULL;',
      '    FILE *in = stdin;',
      '    FILE *out = stdout;',
      '    t_ctx ctx;',
      '    int status = 0;',
      '    int i;',
      '',
      '    if (argc > 0 && argv[0] && argv[0][0])',
      '        progname = argv[0];',
      '',
      '    for (i = 1; i < argc; i++) {',
      '        if (strcmp(argv[i], "-o") == 0) {',
      '            if (++i == argc) {',
      r'                fprintf(stderr, "%s: -o needs a filename\n", progname);',
      '                return 1;',
      '            }',
      '            out_path = argv[i];',
      '        } else if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0) {',
      '            usage(stdout);',
      '            return 0;',
      '        } else if (strcmp(argv[i], "-") == 0) {',
      '            in_path = NULL;             /* explicit stdin */',
      "        } else if (argv[i][0] == '-' && argv[i][1]) {",
      r'            fprintf(stderr, "%s: unknown option: %s\n", progname, argv[i]);',
      '            usage(stderr);',
      '            return 1;',
      '        } else if (in_path == NULL) {',
      '            in_path = argv[i];',
      '        } else {',
      r'            fprintf(stderr, "%s: only one input file may be given\n", progname);',
      '            return 1;',
      '        }',
      '    }',
      '',
      '    if (in_path) {',
      '        in = fopen(in_path, "rb");',
      '        if (!in) {',
      r'            fprintf(stderr, "%s: %s: %s\n", progname, in_path, strerror(errno));',
      '            return 1;',
      '        }',
      '    }',
      '',
      '    if (out_path) {',
      '        out = fopen(out_path, "wb");',
      '        if (!out) {',
      r'            fprintf(stderr, "%s: %s: %s\n", progname, out_path, strerror(errno));',
      '            if (in != stdin)',
      '                fclose(in);',
      '            return 1;',
      '        }',
      '    }',
      '',
      '#ifdef _WIN32',
      '    if (in == stdin)',
      '        _setmode(_fileno(stdin), _O_BINARY);',
      '    if (out == stdout)',
      '        _setmode(_fileno(stdout), _O_BINARY);',
      '#else',
      '    /* Raw samples down a terminal are noise, and usually a forgotten -o. */',
      '    if (out == stdout && isatty(fileno(stdout))) {',
      r'        fprintf(stderr, "%s: refusing to write binary samples to a terminal; "',
      r'                        "use -o or redirect\n", progname);',
      '        if (in != stdin)',
      '            fclose(in);',
      '        return 1;',
      '    }',
      '#endif',
      '',
      '    if (init_filter(&ctx) != 0) {',
      r'        fprintf(stderr, "%s: init_filter: out of memory\n", progname);',
      '        status = 1;',
      '    } else {',
      '        if (filter_stream(in, out, &ctx) != 0)',
      '            status = 1;',
      '        free_filter(&ctx);',
      '    }',
      '',
      '    if (in != stdin)',
      '        fclose(in);',
      '    if (fflush(out) != 0 || (out != stdout && fclose(out) != 0)) {',
      r'        fprintf(stderr, "%s: %s: %s\n", progname,',
      '                out_path ? out_path : "stdout", strerror(errno));',
      '        status = 1;',
      '    }',
      '',
      '    return status;',
      '}',
      '#endif',
      '',
    ].join('\n');

/// A self-contained C implementation of the biquad cascade.
///
/// The inner loop is the same transposed direct form II that `sosFilter` runs
/// and that the design view draws, so the three agree sample for sample. `a0`
/// is divided out here rather than stored, since it is 1 for every section a
/// bilinear design produces.
String iirCSource(iir.IIRResult res, {fx.Fixed? fixed, String name = 'filter'}) {
  final rows = <String>[];
  for (final s in res.sos) {
    final c = [s[0] / s[3], s[1] / s[3], s[2] / s[3], s[4] / s[3], s[5] / s[3]];
    rows.add('    { ${c.map((v) => formatG(v, precision: 17, space: true))
        .join(', ')} },');
  }
  final plural = res.wp.length > 1 ? 's' : '';
  final head = _preamble(
        '${labelOf(res.approximation)} ${res.response} IIR filter, '
            'order ${res.order}',
        [
          'sample rate ${formatG(res.fs)}, '
              'passband edge$plural ${res.wp.map(formatG).join(', ')}, '
              'stopband edge$plural ${res.ws.map(formatG).join(', ')}',
          '${formatG(res.rp)} dB passband ripple, ${formatG(res.rs)} dB '
              'stopband attenuation (achieved '
              '${formatG(res.achievedRp, precision: 4)} dB / '
              '${formatG(res.achievedRs, precision: 4)} dB)',
          'max |pole| = ${formatG(res.maxPoleRadius, precision: 10)}',
          formatNote(fixed),
        ],
        'Cascade of ${res.sos.length} biquads, each transposed direct form II.',
      );
  final body = [
        '#define FILTER_SECTIONS ${res.sos.length}',
        '',
        '/* one row per section: b0, b1, b2, a1, a2   (a0 is 1) */',
        'static const double filter_sos[FILTER_SECTIONS][5] = {',
        ...rows,
        '};',
        '',
        'typedef struct {',
        '    double *state;      /* two delay elements per section */',
        '    size_t  sections;',
        '} t_ctx;',
        '',
        '/* Allocates the filter state, zeroed.  Returns 0, or -1 if out of',
        '   memory, in which case ctx is left safe to pass to free_filter. */',
        'int init_filter(t_ctx *ctx)',
        '{',
        '    ctx->sections = FILTER_SECTIONS;',
        '    ctx->state = (double *) calloc(2 * FILTER_SECTIONS,',
        '                                   sizeof *ctx->state);',
        '    return ctx->state ? 0 : -1;',
        '}',
        '',
        'void free_filter(t_ctx *ctx)',
        '{',
        '    free(ctx->state);',
        '    ctx->state = NULL;',
        '    ctx->sections = 0;',
        '}',
        '',
        '/*  y     = b0*x + s0',
        "    s0'   = b1*x - a1*y + s1",
        "    s1'   = b2*x - a2*y            , section by section  */",
        'double process_sample(double sample, t_ctx *ctx)',
        '{',
        '    size_t i;',
        '',
        '    for (i = 0; i < ctx->sections; i++) {',
        '        const double *c = filter_sos[i];',
        '        double *s = ctx->state + 2 * i;',
        '        double out = c[0] * sample + s[0];',
        '',
        '        s[0] = c[1] * sample - c[3] * out + s[1];',
        '        s[1] = c[2] * sample - c[4] * out;',
        '        sample = out;',
        '    }',
        '    return sample;',
        '}',
  ].join('\n');
  return '$head$body\n${_main(name)}';
}

/// A self-contained C implementation of the tapped delay line.
///
/// The delay line is a circular buffer, so nothing is copied per sample; the
/// loop walks it backwards from the newest sample, which is the order the taps
/// are stored in.
String firCSource(fir.RemezResult res,
    {fx.Fixed? fixed, String name = 'filter'}) {
  final taps = [
    for (final v in res.h) '    ${formatG(v, precision: 17, space: true)},'
  ];
  final band =
      res.bands.map((b) => '${formatG(b.f1)}–${formatG(b.f2)}').join(', ');

  final head = _preamble(
        'Parks-McClellan FIR filter, type ${res.ftype} '
            '(${res.symmetry.name}), N = ${res.numtaps}',
        [
          'sample rate ${formatG(res.fs)}, bands $band',
          'weighted delta = ${formatG(res.delta.abs(), precision: 10)}',
          formatNote(fixed),
        ],
        'Direct form: a tapped delay line into one accumulator.',
      );
  final body = [
        '#define FILTER_TAPS ${res.numtaps}',
        '',
        'static const double filter_taps[FILTER_TAPS] = {',
        ...taps,
        '};',
        '',
        'typedef struct {',
        '    double *state;      /* circular delay line, FILTER_TAPS long */',
        '    size_t  taps;',
        '    size_t  pos;        /* where the next sample goes */',
        '} t_ctx;',
        '',
        '/* Allocates the delay line, zeroed.  Returns 0, or -1 if out of',
        '   memory, in which case ctx is left safe to pass to free_filter. */',
        'int init_filter(t_ctx *ctx)',
        '{',
        '    ctx->taps = FILTER_TAPS;',
        '    ctx->pos = 0;',
        '    ctx->state = (double *) calloc(FILTER_TAPS, sizeof *ctx->state);',
        '    return ctx->state ? 0 : -1;',
        '}',
        '',
        'void free_filter(t_ctx *ctx)',
        '{',
        '    free(ctx->state);',
        '    ctx->state = NULL;',
        '    ctx->taps = ctx->pos = 0;',
        '}',
        '',
        '/*  y[n] = sum_i h[i] * x[n-i]  */',
        'double process_sample(double sample, t_ctx *ctx)',
        '{',
        '    double acc = 0.0;',
        '    size_t i, k;',
        '',
        '    ctx->state[ctx->pos] = sample;',
        '    k = ctx->pos;',
        '    for (i = 0; i < ctx->taps; i++) {',
        '        acc += filter_taps[i] * ctx->state[k];',
        '        k = k ? k - 1 : ctx->taps - 1;',
        '    }',
        '    ctx->pos = ctx->pos + 1 == ctx->taps ? 0 : ctx->pos + 1;',
        '    return acc;',
        '}',
  ].join('\n');
  return '$head$body\n${_main(name)}';
}
