/// The filter in C with no floating point anywhere.
///
/// The ordinary C export computes in doubles, which is what you want on a
/// desktop and useless on a part that has no FPU. This one is the same filter
/// written the way the generated hardware computes it: every value a signed
/// integer of the datapath width, every product rounded to nearest and
/// saturated, every sum saturated, in the order the chosen structure sums them.
///
/// That is not merely "also correct". It is the *same* arithmetic as
/// `datapath.dart`, and so the same as the SystemVerilog and the VHDL, down to
/// the last bit -- including where they clip. Which makes this the reference
/// model you can run on the target before the hardware exists, and the thing
/// to diff against when the hardware does exist and disagrees.
library;

import 'datapath.dart' as dp;
import 'fir_core.dart' as fir;
import 'fixed_point.dart' as fx;
import 'format.dart';
import 'iir_core.dart' as iir;
import 'labels.dart';

/// Raised when there is no integer datapath to write.
class IntCError implements Exception {
  const IntCError(this.message);
  final String message;
  @override
  String toString() => 'IntCError: $message';
}

void _check(fx.Fixed fixed) {
  if (fixed.fracBits < 0) {
    throw IntCError('the binary point is ${-fixed.fracBits} places into the '
        'integer part, which no shift can undo; give the coefficients more '
        'bits');
  }
  if (fixed.saturated > 0) {
    throw IntCError('${fixed.saturated} coefficient(s) saturated when '
        'quantized, so this would not be the filter that was designed');
  }
}

String _header(String title, List<String> detail, int width, int frac) => '''
/*  $title
 *
${detail.map((d) => ' *  $d').join('\n')}
 *
 *  Integer only: no floating point, and no library beyond stdio for the
 *  driver at the bottom.  Arithmetic is the generated hardware's, exactly --
 *  products rounded to nearest and saturated into $width bits, sums saturated
 *  the same, in the order the structure sums them.  Run this and the RTL on
 *  the same samples and every output is identical.
 *
 *  Generated by $programName.
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define FRAC_BITS   $frac
#define DATA_BITS   $width

#define DATA_MIN    (-(INT64_C(1) << (DATA_BITS - 1)))
#define DATA_MAX    ((INT64_C(1) << (DATA_BITS - 1)) - 1)

/*  Saturate into the datapath rather than wrapping.  Wrapping turns a loud
 *  overflow into a sign flip, which sounds like a different filter.
 */
static int32_t sat(int64_t v)
{
    if (v < DATA_MIN) return (int32_t) DATA_MIN;
    if (v > DATA_MAX) return (int32_t) DATA_MAX;
    return (int32_t) v;
}

/*  Exact product, plus half an LSB, shifted down, saturated.
 *
 *  The shift is arithmetic on every compiler that matters and is required to
 *  be by C23; adding the half before it is what makes this round to nearest
 *  rather than towards minus infinity.
 */
static int32_t mul(int32_t coef, int32_t sample)
{
    int64_t p = (int64_t) coef * (int64_t) sample;
#if FRAC_BITS > 0
    p = (p + (INT64_C(1) << (FRAC_BITS - 1))) >> FRAC_BITS;
#endif
    return sat(p);
}

static int32_t addsat(int32_t a, int32_t b)
{
    return sat((int64_t) a + (int64_t) b);
}
''';

/// The FIR, as an exact software model of the datapath the RTL would build.
String firIntCSource(
  fir.RemezResult res, {
  required fx.Fixed fixed,
  int headroom = 2,
  String structure = 'chain',
  bool folded = false,
  String name = 'filter',
}) {
  _check(fixed);
  final width = fixed.bits + headroom;
  if (width > 32) {
    throw IntCError('a ${fixed.bits}-bit word with $headroom bits of headroom '
        'needs a $width-bit datapath, which will not fit an int32_t');
  }
  final kind = dp.structureFromName(structure);
  final terms = dp.firTerms(res.numtaps, res.symmetry, folded);

  final b = StringBuffer(_header(
    'Linear-phase FIR, type ${res.ftype} (${res.symmetry.name}), '
        'N = ${res.numtaps}',
    [
      'sample rate ${formatG(res.fs)}',
      '${fixed.bits}-bit coefficients, ${fixed.qFormat}, '
          '$headroom bit(s) of headroom',
      'structure: ${kind.label}${folded ? ', folded' : ''}, '
          '${terms.length} multiplies per sample',
    ],
    width,
    fixed.fracBits,
  ));

  b.writeln();
  b.writeln('#define FILTER_TAPS  ${res.numtaps}');
  b.writeln('#define FILTER_TERMS ${terms.length}');
  b.writeln();
  b.writeln('static const int32_t filter_taps[FILTER_TAPS] = {');
  for (final v in fixed.ints) {
    b.writeln('    ${v.toString().padLeft(12)},');
  }
  b.writeln('};');
  b.writeln();
  b.writeln('typedef struct {');
  b.writeln('    int32_t line[FILTER_TAPS];  /* newest sample at [0] */');
  b.writeln('} t_ctx;');
  b.writeln();
  b.writeln('void init_filter(t_ctx *ctx)');
  b.writeln('{');
  b.writeln('    memset(ctx, 0, sizeof *ctx);');
  b.writeln('}');
  b.writeln();
  b.writeln('int32_t process_sample(int32_t sample, t_ctx *ctx)');
  b.writeln('{');
  b.writeln('    int32_t products[FILTER_TERMS];');
  b.writeln('    int32_t acc;');
  b.writeln('    size_t i;');
  b.writeln();
  b.writeln('    for (i = FILTER_TAPS - 1; i > 0; i--)');
  b.writeln('        ctx->line[i] = ctx->line[i - 1];');
  b.writeln('    ctx->line[0] = sat(sample);');
  b.writeln();
  for (var t = 0; t < terms.length; t++) {
    final term = terms[t];
    if (term.taps.length == 1) {
      b.writeln('    products[$t] = mul(filter_taps[${term.coefIndex}], '
          'ctx->line[${term.taps[0]}]);');
    } else {
      // One bit wider than the datapath and deliberately not saturated: it
      // sums two samples that may each be at full scale, and clipping that
      // would throw signal away instead of rounding it.
      b.writeln('    products[$t] = mul(filter_taps[${term.coefIndex}], '
          '(int32_t) ((int64_t) ctx->line[${term.taps[0]}] '
          '${term.sign < 0 ? '-' : '+'} (int64_t) ctx->line[${term.taps[1]}]));');
    }
  }
  b.writeln();
  if (kind == dp.Structure.tree) {
    b.writeln('    /*  Balanced tree: the sums saturate, and saturating adds');
    b.writeln('     *  are not associative, so the pairing is part of the');
    b.writeln('     *  specification and not an optimisation.');
    b.writeln('     */');
    b.writeln('    {');
    b.writeln('        int32_t level[FILTER_TERMS];');
    b.writeln('        size_t n = FILTER_TERMS, out;');
    b.writeln('        memcpy(level, products, sizeof products);');
    b.writeln('        while (n > 1) {');
    b.writeln('            out = 0;');
    b.writeln('            for (i = 0; i + 1 < n; i += 2)');
    b.writeln('                level[out++] = addsat(level[i], level[i + 1]);');
    b.writeln('            if (n & 1) level[out++] = level[n - 1];');
    b.writeln('            n = out;');
    b.writeln('        }');
    b.writeln('        acc = level[0];');
    b.writeln('    }');
  } else {
    b.writeln('    /*  In tap order, one adder per term: what the chain and');
    b.writeln('     *  the mac structures both compute.');
    b.writeln('     */');
    b.writeln('    acc = products[0];');
    b.writeln('    for (i = 1; i < FILTER_TERMS; i++)');
    b.writeln('        acc = addsat(acc, products[i]);');
  }
  b.writeln();
  b.writeln('    return acc;');
  b.writeln('}');
  b.writeln();
  b.write(_driver(name, 'process_sample(v, &ctx)'));
  return b.toString();
}

/// The biquad cascade, transposed direct form II, in integers.
String iirIntCSource(
  iir.IIRResult res, {
  required fx.Fixed fixed,
  int headroom = 2,
  String name = 'filter',
}) {
  _check(fixed);
  final width = fixed.bits + headroom;
  if (width > 32) {
    throw IntCError('a ${fixed.bits}-bit word with $headroom bits of headroom '
        'needs a $width-bit datapath, which will not fit an int32_t');
  }

  final b = StringBuffer(_header(
    '${labelOf(res.approximation)} ${res.response}, order ${res.order}',
    [
      'sample rate ${formatG(res.fs)}',
      '${fixed.bits}-bit coefficients, ${fixed.qFormat}, '
          '$headroom bit(s) of headroom',
      'cascade of ${res.sos.length} biquad(s), transposed direct form II',
    ],
    width,
    fixed.fracBits,
  ));

  b.writeln();
  b.writeln('#define IIR_SECTIONS ${res.sos.length}');
  b.writeln();
  b.writeln('/*  b0 b1 b2 a1 a2 per section.  a0 is 1 and nothing multiplies');
  b.writeln(' *  by it; a1 and a2 are stored as designed and negated in the');
  b.writeln(' *  recurrence, which is where the feedback subtracts.');
  b.writeln(' */');
  b.writeln('static const int32_t iir_coeffs[IIR_SECTIONS][5] = {');
  for (var s = 0; s < res.sos.length; s++) {
    final row = [0, 1, 2, 4, 5]
        .map((c) => fixed.ints[s * 6 + c].toString().padLeft(12))
        .join(', ');
    b.writeln('    {$row},');
  }
  b.writeln('};');
  b.writeln();
  b.writeln('typedef struct {');
  b.writeln('    int32_t state[IIR_SECTIONS][2];');
  b.writeln('} t_ctx;');
  b.writeln();
  b.writeln('void init_filter(t_ctx *ctx)');
  b.writeln('{');
  b.writeln('    memset(ctx, 0, sizeof *ctx);');
  b.writeln('}');
  b.writeln();
  b.writeln('int32_t process_sample(int32_t sample, t_ctx *ctx)');
  b.writeln('{');
  b.writeln('    int32_t value = sat(sample);');
  b.writeln('    size_t i;');
  b.writeln();
  b.writeln('    for (i = 0; i < IIR_SECTIONS; i++) {');
  b.writeln('        int32_t b0 = iir_coeffs[i][0], b1 = iir_coeffs[i][1];');
  b.writeln('        int32_t b2 = iir_coeffs[i][2], a1 = iir_coeffs[i][3];');
  b.writeln('        int32_t a2 = iir_coeffs[i][4];');
  b.writeln('        int32_t s1 = ctx->state[i][0], s2 = ctx->state[i][1];');
  b.writeln('        int32_t y  = addsat(mul(b0, value), s1);');
  b.writeln('        int32_t u1 = addsat(mul(b1, value), mul(sat(-a1), y));');
  b.writeln('        ctx->state[i][0] = addsat(u1, s2);');
  b.writeln('        ctx->state[i][1] = addsat(mul(b2, value), '
      'mul(sat(-a2), y));');
  b.writeln('        value = y;');
  b.writeln('    }');
  b.writeln('    return value;');
  b.writeln('}');
  b.writeln();
  b.write(_driver(name, 'process_sample(v, &ctx)'));
  return b.toString();
}

/// A driver that filters raw 32-bit samples on stdin to stdout.
///
/// Raw rather than text so a testbench's vectors go straight in, and so the
/// bytes on the way out can be compared with the RTL's without a decimal
/// conversion in between deciding what "equal" means.
String _driver(String name, String call) => '''

/*  ------------------------------------------------------------------
 *  A driver, so this file is something you can run as well as link.
 *
 *      $name < in.i32 > out.i32
 *
 *  Little-endian int32 in, little-endian int32 out, one for one.
 *  Delete everything below this line to use it as a library.
 *  ------------------------------------------------------------------
 */

int main(int argc, char **argv)
{
    t_ctx ctx;
    int32_t v;

    (void) argv;
    if (argc > 1) {
        fprintf(stderr, "usage: $name < in.i32 > out.i32\\n");
        return 2;
    }
    init_filter(&ctx);
    while (fread(&v, sizeof v, 1, stdin) == 1) {
        int32_t y = $call;
        if (fwrite(&y, sizeof y, 1, stdout) != 1) {
            fprintf(stderr, "$name: write failed\\n");
            return 1;
        }
    }
    return 0;
}
''';
