/// The design as a script, for the two environments most filters end up in.
///
/// Neither of these is a filter implementation to be proud of -- they call the
/// library routine and get out of the way. That is the point: what a NumPy or
/// MATLAB user wants from this program is the coefficients, in a file they can
/// run without retyping seventeen digits, and a line showing which library call
/// expects them in that shape. An FIR goes to `lfilter`/`filter` with a
/// denominator of 1; a cascade goes to `sosfilt`, which is the only form that
/// keeps a high-order design stable.
library;

import 'fir_core.dart' as fir;
import 'fixed_point.dart' as fx;
import 'format.dart';
import 'iir_core.dart' as iir;
import 'labels.dart';

/// Which language a path asks for, or null if it asks for neither.
String? scriptLanguageFor(String path) {
  final lower = path.toLowerCase();
  if (lower.endsWith('.py')) return 'python';
  if (lower.endsWith('.m')) return 'matlab';
  return null;
}

String firScript(fir.RemezResult res, String language,
        {fx.Fixed? fixed, String name = 'filter'}) =>
    language == 'matlab'
        ? _firMatlab(res, fixed, name)
        : _firPython(res, fixed, name);

String iirScript(iir.IIRResult res, String language,
        {fx.Fixed? fixed, String name = 'filter'}) =>
    language == 'matlab'
        ? _iirMatlab(res, fixed, name)
        : _iirPython(res, fixed, name);

// ---------------------------------------------------------------------------
// Python
// ---------------------------------------------------------------------------

String _firPython(fir.RemezResult res, fx.Fixed? fixed, String name) {
  final b = StringBuffer();
  b.writeln('"""${_firTitle(res)}');
  b.writeln();
  b.writeln('Generated by $programName.  ${_note(fixed)}');
  b.writeln('"""');
  b.writeln();
  b.writeln('import numpy as np');
  b.writeln();
  b.writeln('FS = ${formatG(res.fs, precision: 17)}');
  b.writeln('TAPS = np.array([');
  for (final v in res.h) {
    b.writeln('    ${formatG(v, precision: 17)},');
  }
  b.writeln('])');
  if (fixed != null) {
    b.writeln();
    b.writeln('FRAC_BITS = ${fixed.fracBits}');
    b.writeln('# The stored integers: TAPS == TAPS_Q / 2**FRAC_BITS exactly.');
    b.writeln('TAPS_Q = np.array([${fixed.ints.join(', ')}])');
  }
  b.writeln();
  b.writeln('''

def $name(x):
    """Filter x, returning as many samples as went in.

    An FIR is a convolution, and `np.convolve` in 'full' mode returns the
    whole thing, tail included.  Trimming to len(x) is what makes this the
    same stream-oriented filter the C and RTL exports implement, with the
    (N-1)/2 samples of group delay still in it.
    """
    return np.convolve(np.asarray(x, dtype=float), TAPS)[:len(x)]


def response(points=1024):
    """Magnitude response over 0..FS/2, as (frequency, dB)."""
    w = np.linspace(0.0, np.pi, points)
    h = np.exp(-1j * np.outer(w, np.arange(TAPS.size))) @ TAPS
    return w * FS / (2 * np.pi), 20 * np.log10(np.maximum(np.abs(h), 1e-300))
''');
  return b.toString();
}

String _iirPython(iir.IIRResult res, fx.Fixed? fixed, String name) {
  final b = StringBuffer();
  b.writeln('"""${_iirTitle(res)}');
  b.writeln();
  b.writeln('Generated by $programName.  ${_note(fixed)}');
  b.writeln('"""');
  b.writeln();
  b.writeln('import numpy as np');
  b.writeln('from scipy.signal import sosfilt, sosfreqz');
  b.writeln();
  b.writeln('FS = ${formatG(res.fs, precision: 17)}');
  b.writeln('# Second-order sections, b0 b1 b2 a0 a1 a2 -- the layout scipy');
  b.writeln('# expects, and the only form that keeps this order stable.');
  b.writeln('SOS = np.array([');
  for (final s in res.sos) {
    b.writeln('    [${s.map((v) => formatG(v, precision: 17)).join(', ')}],');
  }
  b.writeln('])');
  if (fixed != null) {
    b.writeln();
    b.writeln('FRAC_BITS = ${fixed.fracBits}');
    b.writeln('SOS_Q = np.array([');
    for (var i = 0; i < res.sos.length; i++) {
      b.writeln('    [${_sectionInts(fixed, i).join(', ')}],');
    }
    b.writeln('])');
  }
  b.writeln();
  b.writeln('''

def $name(x):
    """Filter x through the cascade."""
    return sosfilt(SOS, np.asarray(x, dtype=float))


def response(points=1024):
    """Magnitude response over 0..FS/2, as (frequency, dB)."""
    w, h = sosfreqz(SOS, worN=points)
    return w * FS / (2 * np.pi), 20 * np.log10(np.maximum(np.abs(h), 1e-300))
''');
  return b.toString();
}

// ---------------------------------------------------------------------------
// MATLAB
// ---------------------------------------------------------------------------

String _firMatlab(fir.RemezResult res, fx.Fixed? fixed, String name) {
  final b = StringBuffer();
  b.writeln('function y = $name(x)');
  b.writeln('%$name  ${_firTitle(res)}');
  b.writeln('%');
  b.writeln('%   Generated by $programName.  ${_note(fixed)}');
  b.writeln('%   y = $name(x) filters x and returns as many samples as went');
  b.writeln('%   in, with the (N-1)/2 samples of group delay still in it.');
  b.writeln();
  b.writeln('fs = ${formatG(res.fs, precision: 17)}; %#ok<NASGU>');
  b.writeln('h = [ ...');
  for (final v in res.h) {
    b.writeln('    ${formatG(v, precision: 17)}; ...');
  }
  b.writeln('];');
  if (fixed != null) {
    b.writeln();
    b.writeln('% The stored integers: h == hq / 2^${fixed.fracBits} exactly.');
    b.writeln('fracBits = ${fixed.fracBits}; %#ok<NASGU>');
    b.writeln('hq = [${fixed.ints.join('; ')}]; %#ok<NASGU>');
  }
  b.writeln();
  b.writeln('% An FIR is a filter with a denominator of 1.');
  b.writeln('y = filter(h, 1, x);');
  b.writeln('end');
  return b.toString();
}

String _iirMatlab(iir.IIRResult res, fx.Fixed? fixed, String name) {
  final b = StringBuffer();
  b.writeln('function y = $name(x)');
  b.writeln('%$name  ${_iirTitle(res)}');
  b.writeln('%');
  b.writeln('%   Generated by $programName.  ${_note(fixed)}');
  b.writeln('%   Kept as second-order sections rather than one transfer');
  b.writeln('%   function: at this order the flattened polynomial loses its');
  b.writeln('%   roots to rounding and the filter stops being stable.');
  b.writeln();
  b.writeln('fs = ${formatG(res.fs, precision: 17)}; %#ok<NASGU>');
  b.writeln('sos = [ ...');
  for (final s in res.sos) {
    b.writeln('    ${s.map((v) => formatG(v, precision: 17)).join(', ')}; ...');
  }
  b.writeln('];');
  if (fixed != null) {
    b.writeln();
    b.writeln('fracBits = ${fixed.fracBits}; %#ok<NASGU>');
    b.writeln('sosq = [ ...');
    for (var i = 0; i < res.sos.length; i++) {
      b.writeln('    ${_sectionInts(fixed, i).join(', ')}; ...');
    }
    b.writeln(']; %#ok<NASGU>');
  }
  b.writeln();
  b.writeln('y = sosfilt(sos, x);');
  b.writeln('end');
  return b.toString();
}

// ---------------------------------------------------------------------------

String _firTitle(fir.RemezResult res) =>
    'Linear-phase FIR, type ${res.ftype} (${res.symmetry.name}), '
    'N = ${res.numtaps}';

String _iirTitle(iir.IIRResult res) =>
    '${labelOf(res.approximation)} ${res.response}, order ${res.order}, '
    '${res.sos.length} biquad(s)';

String _note(fx.Fixed? fixed) => fixed == null
    ? 'Double-precision coefficients.'
    : '${fixed.bits}-bit fixed point, ${fixed.qFormat}.';

List<int> _sectionInts(fx.Fixed fixed, int section) =>
    [for (var c = 0; c < 6; c++) fixed.ints[section * 6 + c]];
